In [1]:
import pandas as pd
from pathlib import Path
import numpy as np
import seaborn as sns

# from posydon.popsyn.binarypopulation import BinaryPopulation
# from posydon.binary_evol.binarystar import BinaryStar
# from posydon.binary_evol.singlestar import SingleStar
from posydon.popsyn.synthetic_population import Population
# from posydon.popsyn.synthetic_population import PopulationRunner
# import astropy.units as u

# import os
# import shutil
# from posydon.config import PATH_TO_POSYDON

from POSYDONHRDiagramModule import HR_Diagram

import matplotlib.pyplot as plt

import random as rand 

from collections import Counter

DataPath = Path().resolve().parent / 'Data'

In [2]:
cols = ['time', 'step_names', 'state', 
        'event', 'S1_state', 'S2_state', 
        'S1_mass', 'S2_mass', 'orbital_period']
finCols = [
    'orbital_period_f',
    'eccentricity_f',
    'state_f',

    'S1_state_f',
    'S2_state_f',
    
    'S2_mass_f',
    'S2_log_R_f',
    'S2_log_L_f',


    'S1_mass_f',
    'S1_log_R_f',
    'S1_log_L_f'

 ]

initCols = [
    'orbital_period_i',
    'eccentricity_i',
    'state_i',

    'S2_state_i',
    'S2_mass_i',
    'S2_log_R_i',

    'S1_state_i',
    'S1_mass_i',
    'S1_log_R_i'
 ]

In [3]:
pop = Population('/home/bku2126/b1095/bku2126/stellarBHs/grids/g2/1e+00_Zsun_population.h5')
# pop.calculate_formation_channels()
# merged = pop.oneline.select("state_f == merged")

In [ ]:
randSamp10k_i = pop.oneline.select().sample(10000, random_state = 42).index.to_list()
pop.export_selection(randSamp10k_i, '/home/bku2126/b1095/bku2126/bns-offsets/data/10kSample.h5')

In [7]:
randSamp1k_i = pop.oneline.select().sample(1000, random_state = 42).index.to_list()
pop.export_selection(randSamp1k_i, '/home/bku2126/b1095/bku2126/bns-offsets/data/1kSample.h5', overwrite = True)

In [8]:
randSamp100_i = pop.oneline.select().sample(100, random_state = 42).index.to_list()
pop.export_selection(randSamp100_i, '/home/bku2126/b1095/bku2126/bns-offsets/data/100Sample.h5', overwrite = True)

In [4]:
bh_bh = pop.oneline.select("(S1_state_f == BH) & (S2_state_f == BH) & (state_f == detached)")

In [11]:
bhbhexport_sample = bh_bh.sample(100,random_state = 42).index.to_list()

In [16]:
pop.export_selection(bhbhexport_sample, '/home/bku2126/b1095/bku2126/stellarBHs/Data/bhbh100.h5')

In [50]:
# pop.export_selection(merged.index.to_list(), '/home/bku2126/b1095/bku2126/stellarBHs/Data/oneMillMerged.h5')

In [51]:
pop = Population('/home/bku2126/b1095/bku2126/stellarBHs/Data/oneMillMerged.h5')

In [52]:
bhSolPop = Population('/home/bku2126/b1095/bku2126/stellarBHs/Data/10MillFilt/BH_Sol_Filtered_1e+00_Zsun_population.h5')

Missing ini parameter: posydon_version

In [53]:
bhSolPop.history.select()[cols]

,time,step_names,state,event,S1_state,S2_state,S1_mass,S2_mass,orbital_period
binary_index,,,,,,,,,
0,8.986912e+09,initial_cond,detached,ZAMS,H-rich_Core_H_burning,H-rich_Core_H_burning,17.461032,2.042611,4138.854009
0,8.999785e+09,step_HMS_HMS,RLO1,oCE1,H-rich_Core_He_depleted,H-rich_Core_H_burning,10.229369,2.066664,3817.968618
0,8.999785e+09,step_CE,detached,NaN,stripped_He_Core_He_depleted,H-rich_Core_H_burning,8.120438,2.066664,1.594205
0,8.999790e+09,step_detached,detached,CC1,stripped_He_Core_He_depleted,H-rich_Core_H_burning,8.040238,2.188440,1.599223
0,8.999790e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,4.497844,2.188440,2.759667
...,...,...,...,...,...,...,...,...,...
106,7.274039e+09,step_detached,RLO2,oRLO2,BH,H-rich_Shell_H_burning,4.498007,2.627800,11.708655
106,7.469879e+09,step_CO_HMS_RLO,detached,CC2,BH,H-rich_Core_He_depleted,5.436030,0.509444,529.886930
106,7.469879e+09,step_SN,detached,NaN,BH,WD,5.436030,0.454437,539.909522
106,1.380000e+10,step_dco,detached,maxtime,BH,WD,5.436030,0.454437,539.909520
106,1.380000e+10,step_end,detached,END,BH,WD,5.436030,0.454437,539.909520

In [54]:
df = pd.read_csv('/home/bku2126/b1095/bku2126/stellarBHs/Data/10MillFilt/BH_Sol_Filtered_1e+00_Zsun_population.csv')

In [55]:
df

,binary_index,state,event,time,separation,orbital_period,eccentricity,rl_relative_overflow_1,rl_relative_overflow_2,lg_mtransfer_rate,...,S2_conv_env_turnover_time_l_b,S2_conv_env_turnover_time_l_t,S2_envelope_binding_energy,S2_mass_conv_reg_fortides,S2_thickness_conv_reg_fortides,S2_radius_conv_reg_fortides,S2_lambda_CE_1cent,S2_lambda_CE_10cent,S2_lambda_CE_30cent,S2_lambda_CE_pure_He_star_10cent
0,98167,detached,NaN,8.999790e+09,15.592295,2.759667,0.351460,NaN,NaN,NaN,...,0.000000,0.000000,-1.060802e+49,1.376460e-09,0.003673,1.596058,1.059250,1.059250,1.059250,1.059250
1,164933,detached,NaN,5.320878e+09,23.548169,5.665033,0.393018,NaN,NaN,NaN,...,0.000000,0.000000,-1.306797e+49,1.275745e-09,0.003705,1.749940,1.087898,1.087898,1.087898,1.087898
2,421025,detached,NaN,8.501130e+09,56.874522,19.815499,0.541184,NaN,NaN,NaN,...,0.000000,0.000000,-1.074448e+49,1.368844e-09,0.003717,1.604894,1.060897,1.060897,1.060897,1.060897
3,432008,detached,NaN,7.629853e+07,6.833317,0.876181,0.250778,NaN,NaN,NaN,...,0.000114,2289.310733,-5.554021e+48,4.375370e-08,0.018593,1.386301,0.976688,0.976688,0.976688,0.976688
4,469540,detached,NaN,4.671309e+09,30.960643,7.931873,0.062861,NaN,NaN,NaN,...,0.000000,0.000000,-1.389527e+49,1.257137e-09,0.003917,1.801025,1.096518,1.096518,1.096518,1.096518
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102,9869876,detached,NaN,7.958286e+09,176.651172,109.989868,0.886831,NaN,NaN,NaN,...,0.000000,0.000000,-1.093747e+49,1.358731e-09,0.003729,1.617445,1.063203,1.063203,1.063203,1.063203
103,9893810,detached,NaN,5.797456e+09,47.100819,13.746755,0.431066,NaN,NaN,NaN,...,0.000000,0.000000,-1.542464e+49,1.212454e-09,0.003906,1.882450,1.113239,1.113239,1.113239,1.113239
104,9898281,detached,NaN,6.978108e+09,28.385943,6.730866,0.105824,NaN,NaN,NaN,...,0.000000,0.000000,-1.483731e+49,1.233944e-09,0.003928,1.855052,1.106384,1.106384,1.106384,1.106384
105,9912445,detached,NaN,3.801350e+09,84.011404,36.878780,0.713982,NaN,NaN,NaN,...,0.000000,0.000000,-9.481873e+48,1.490166e-09,0.003777,1.534551,1.042847,1.042847,1.042847,1.042847
106,9914475,detached,NaN,6.808599e+09,155.913807,84.545141,0.735205,NaN,NaN,NaN,...,0.000000,0.000000,-1.340145e+49,1.255953e-09,0.003794,1.763582,1.092643,1.092643,1.092643,1.092643

In [56]:
pop.oneline.select()

,state_i,event_i,time_i,orbital_period_i,eccentricity_i,lg_mtransfer_rate_i,step_names_i,step_times_i,S1_state_i,S1_mass_i,...,interp_class_CO_HMS_RLO,interp_class_CO_HeMS,interp_class_CO_HeMS_RLO,mt_history_HMS_HMS,mt_history_CO_HMS_RLO,mt_history_CO_HeMS,mt_history_CO_HeMS_RLO,FAILED,WARNING,metallicity
binary_index,,,,,,,,,,,,,,,,,,,,,
0,detached,ZAMS,1.127619e+10,7.882748,0.071952,NaN,initial_cond,0.0,H-rich_Core_H_burning,17.031616,...,NaN,NaN,NaN,Unstable RLOF during MS,NaN,NaN,NaN,0,1,1.0
1,detached,ZAMS,5.837792e+09,53.448491,0.779123,NaN,initial_cond,0.0,H-rich_Core_H_burning,25.301711,...,NaN,NaN,NaN,Unstable RLOF during postMS,NaN,NaN,NaN,0,1,1.0
2,detached,ZAMS,9.932242e+09,2916.894296,0.769472,NaN,initial_cond,0.0,H-rich_Core_H_burning,14.725529,...,NaN,NaN,NaN,Unstable RLOF during postMS,NaN,NaN,NaN,0,1,1.0
3,detached,ZAMS,9.678377e+09,199.614917,0.259798,NaN,initial_cond,0.0,H-rich_Core_H_burning,16.884533,...,unstable_MT,NaN,NaN,Unstable RLOF during postMS,Unstable RLOF during MS,NaN,NaN,0,1,1.0
4,detached,ZAMS,5.456018e+09,92.135975,0.784805,NaN,initial_cond,0.0,H-rich_Core_H_burning,36.134321,...,NaN,NaN,NaN,Unstable RLOF during postMS,NaN,NaN,NaN,0,1,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
264596,detached,ZAMS,6.029655e+09,239.191571,0.544035,NaN,initial_cond,0.0,H-rich_Core_H_burning,19.902530,...,NaN,NaN,NaN,Unstable RLOF during postMS,NaN,NaN,NaN,0,1,1.0
264597,detached,ZAMS,5.553193e+09,674.308961,0.721780,NaN,initial_cond,0.0,H-rich_Core_H_burning,32.653528,...,NaN,NaN,NaN,Unstable RLOF during postMS,NaN,NaN,NaN,0,1,1.0
264598,detached,ZAMS,7.110186e+09,444.728885,0.846361,NaN,initial_cond,0.0,H-rich_Core_H_burning,16.752196,...,NaN,NaN,NaN,Unstable RLOF during postMS,NaN,NaN,NaN,0,1,1.0
264599,detached,ZAMS,7.026118e+09,65.105656,0.767298,NaN,initial_cond,0.0,H-rich_Core_H_burning,14.794842,...,NaN,NaN,NaN,Unstable RLOF during postMS,NaN,NaN,NaN,0,1,1.0
264600,detached,ZAMS,5.681885e+09,164.264850,0.208651,NaN,initial_cond,0.0,H-rich_Core_H_burning,17.371788,...,NaN,NaN,NaN,Unstable RLOF during postMS,NaN,NaN,NaN,0,1,1.0

In [57]:
bhSolPop.oneline.select()

,state_i,event_i,time_i,separation_i,orbital_period_i,eccentricity_i,rl_relative_overflow_1_i,rl_relative_overflow_2_i,lg_mtransfer_rate_i,step_names_i,...,interp_class_CO_HMS_RLO,interp_class_CO_HeMS,interp_class_CO_HeMS_RLO,mt_history_HMS_HMS,mt_history_CO_HMS_RLO,mt_history_CO_HeMS,mt_history_CO_HeMS_RLO,FAILED,WARNING,metallicity
binary_index,,,,,,,,,,,,,,,,,,,,,
0,detached,ZAMS,8.986912e+09,2919.300237,4138.854009,0.0,NaN,NaN,NaN,initial_cond,...,stable_MT,NaN,NaN,Unstable RLOF during postMS,Last stable RLOF during postMS,NaN,NaN,0,1,1.0
1,detached,ZAMS,5.307688e+09,2931.796105,4214.058792,0.0,NaN,NaN,NaN,initial_cond,...,stable_MT,NaN,NaN,Unstable RLOF during postMS,Last stable RLOF during postMS,NaN,NaN,0,1,1.0
2,detached,ZAMS,8.486257e+09,2845.924808,4123.090826,0.0,NaN,NaN,NaN,initial_cond,...,stable_MT,NaN,NaN,Unstable RLOF during postMS,Last stable RLOF during postMS,NaN,NaN,0,1,1.0
3,detached,ZAMS,6.315842e+07,2981.541957,4342.833283,0.0,NaN,NaN,NaN,initial_cond,...,NaN,NaN,NaN,Unstable RLOF during postMS,NaN,NaN,NaN,0,1,1.0
4,detached,ZAMS,4.657077e+09,2877.764076,4127.376889,0.0,NaN,NaN,NaN,initial_cond,...,stable_MT,NaN,NaN,Unstable RLOF during postMS,Last stable RLOF during postMS,NaN,NaN,0,1,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102,detached,ZAMS,7.942877e+09,2845.694725,4159.486756,0.0,NaN,NaN,NaN,initial_cond,...,stable_MT,NaN,NaN,Unstable RLOF during postMS,Last stable RLOF during postMS,NaN,NaN,0,1,1.0
103,detached,ZAMS,5.785051e+09,2896.943115,3966.766286,0.0,NaN,NaN,NaN,initial_cond,...,stable_MT,NaN,NaN,Unstable RLOF during postMS,Last stable RLOF during postMS,NaN,NaN,0,1,1.0
104,detached,ZAMS,6.964517e+09,2879.043280,4059.758619,0.0,NaN,NaN,NaN,initial_cond,...,stable_MT,NaN,NaN,Unstable RLOF during postMS,Last stable RLOF during postMS,NaN,NaN,0,1,1.0
105,detached,ZAMS,3.786517e+09,2912.513384,4308.784509,0.0,NaN,NaN,NaN,initial_cond,...,stable_MT,NaN,NaN,Unstable RLOF during postMS,Last stable RLOF during postMS,NaN,NaN,0,1,1.0
106,detached,ZAMS,6.794610e+09,2838.121518,3989.468034,0.0,NaN,NaN,NaN,initial_cond,...,stable_MT,NaN,NaN,Unstable RLOF during postMS,Last stable RLOF during postMS,NaN,NaN,0,1,1.0

In [58]:
bhSolPop.oneline.select()[initCols].describe()

,orbital_period_i,eccentricity_i,S2_mass_i,S2_log_R_i,S1_mass_i,S1_log_R_i
count,107.000000,107.0,107.000000,107.0,107.000000,107.0
mean,4079.427748,0.0,2.269078,0.0,16.729035,0.0
std,576.479870,0.0,0.554295,0.0,1.008902,0.0
min,17.828069,0.0,1.615385,0.0,14.601914,0.0
25%,4032.185001,0.0,1.967630,0.0,16.000921,0.0
50%,4161.095349,0.0,2.224593,0.0,16.618007,0.0
75%,4271.339436,0.0,2.451451,0.0,17.282941,0.0
max,4392.380851,0.0,6.285087,0.0,21.171676,0.0

In [59]:
df = pop.history.select()
df2 = df[df['step_names'] =='step_CE']

In [60]:
df = df2[df2['state'] =='merged']

In [61]:
# df.to_csv('/home/bku2126/b1095/bku2126/stellarBHs/Data/merging.csv')

In [72]:
### merged pop

pop_merged = Population(str(DataPath / '/home/bku2126/b1095/bku2126/stellarBHs/Data/oneMillMerged.h5'))

pOneline_merged = pop_merged.oneline.select()

pHistory_merged = pop_merged.history.select()

In [73]:
pOneline_merged = pOneline_merged[pOneline_merged['S1_mass_i'] > 10]
pOneline_merged = pOneline_merged[pOneline_merged['S1_mass_i'] < 22]

pOneline_merged = pOneline_merged[pOneline_merged['S2_mass_i'] > 1]
pOneline_merged = pOneline_merged[pOneline_merged['S2_mass_i'] < 7]

pOneline_merged= pOneline_merged[pOneline_merged['orbital_period_i'] > 3800]
pOneline_merged= pOneline_merged[pOneline_merged['orbital_period_i'] < 4400]

pOneline_merged_sample = pOneline_merged

In [74]:
pOneline_merged_sample

pop_merged.export_selection(pOneline_merged_sample.index.to_list(), '/home/bku2126/b1095/bku2126/stellarBHs/Data/failedSystems_wideConstrain.h5', overwrite=True)

In [65]:
oneline10 = pop10.oneline.select()

NameError: name 'pop10' is not defined

In [ ]:
oneline10[initCols]['S2_mass_i'].describe()

NameError: name 'oneline10' is not defined

In [ ]:
oneline10[initCols]['S1_mass_i'].describe()

NameError: name 'oneline10' is not defined

In [ ]:
Counter(pop.formation_channels['channel'])

Counter({'ZAMS_CC1_END': 297605,
         'ZAMS_oCE1_oMerging1_CC1_END': 233639,
         'ZAMS_oRLO1_CC1_CC2_END': 173762,
         'ZAMS_oRLO1_CC1_oRLO2_CC2_END': 57603,
         'ZAMS_CC1_CC2_END': 48012,
         'ZAMS_oRLO1_CC1_oRLO2_CC2_maxtime_END': 34596,
         'ZAMS_oRLO1_CC1_oRLO2_oCE2_oMerging2_END': 17539,
         'ZAMS_oCE1_END': 16979,
         'ZAMS_FAILED_FAILED': 15966,
         'ZAMS_CC1_oRLO2_CC2_END': 15540,
         'ZAMS_oRLO1_CC1_END': 14225,
         'ZAMS_oCE1_CC1_CC2_END': 12570,
         'ZAMS_CC1_oRLO2_CC2_maxtime_END': 11591,
         'ZAMS_oCE2_oMerging2_CC2_END': 7906,
         'ZAMS_oRLO1-reverse_CC1_CC2_END': 6264,
         'ZAMS_oCE1_FAILED_FAILED': 4566,
         'ZAMS_oRLO1_CC1_oRLO2_oCE2_CC2_END': 4383,
         'ZAMS_CC1_CC2_maxtime_END': 3861,
         'ZAMS_oCE1_CC1_oRLO2_oCE2_oMerging2_END': 2949,
         'ZAMS_oRLO1-reverse_CC1_CC2_maxtime_END': 2933,
         'ZAMS_oCE1_CC1_END': 2326,
         'ZAMS_oDoubleCE2_oMerging2_CC2_END': 1744,
         'ZAMS_oCE1_CC1_oRLO2_CC2_maxtime_END': 1430,
         'ZAMS_oRLO1-reverse_CC1_END': 1339,
         'ZAMS_oRLO1_CC1_oRLO2_oCE2_CC2_maxtime_END': 1241,
         'ZAMS_oRLO1_CC1_oRLO2_oCE2_END': 923,
         'ZAMS_oRLO1_CC1_CC2_maxtime_END': 904,
         'ZAMS_CC1_maxtime_END': 584,
         'ZAMS_oRLO1_CC1_maxtime_END': 559,
         'ZAMS_maxtime_END': 533,
         'ZAMS_END': 431,
         'ZAMS_CC1_oRLO2_oCE2_oMerging2_END': 350,
         'ZAMS_oRLO1-contact_CC1_CC2_END': 343,
         'ZAMS_oRLO1_maxtime_END': 275,
         'ZAMS_oDoubleCE1_oMerging1_CC1_END': 275,
         'ZAMS_oDoubleCE1_CC1_CC2_END': 232,
         'ZAMS_oRLO1-contact_CC1_END': 227,
         'ZAMS_oCE1_CC1_oRLO2_CC2_END': 211,
         'ZAMS_oDoubleCE2_CC1_CC2_maxtime_END': 210,
         'ZAMS_oCE2_FAILED_FAILED': 209,
         'ZAMS_oCE1_oMerging1_FAILED_FAILED': 194,
         'ZAMS_oCE2_CC2_CC1_END': 186,
         'ZAMS_oRLO1-contact_CC1_CC2_maxtime_END': 182,
         'ZAMS_oRLO1-reverse_CC1_oRLO2_CC2_maxtime_END': 147,
         'ZAMS_oCE1_CC1_maxtime_END': 143,
         'ZAMS_oDoubleCE2_oRLO1_FAILED_FAILED': 138,
         'ZAMS_oCE1_CC1_CC2_maxtime_END': 125,
         'ZAMS_oDoubleCE1_FAILED': 120,
         'ZAMS_oCE2_END': 118,
         'ZAMS_oDoubleCE2_CC2_CC1_maxtime_END': 115,
         'ZAMS_oRLO1-contact_CC1_oRLO2_CC2_maxtime_END': 104,
         'ZAMS_oDoubleCE1_CC2_CC1_END': 102,
         'ZAMS_oCE2_CC2_CC1_maxtime_END': 94,
         'ZAMS_oDoubleCE2_CC1_CC2_END': 94,
         'ZAMS_oRLO1-reverse_CC1_oRLO2_CC2_END': 85,
         'ZAMS_oRLO1-reverse_CC1_oRLO2_oCE2_oMerging2_END': 76,
         'ZAMS_oDoubleCE1_CC1_CC2_maxtime_END': 56,
         'ZAMS_oRLO1-reverse_CC1_FAILED': 54,
         'ZAMS_oRLO1-reverse_CC1_FAILED_FAILED': 51,
         'ZAMS_oDoubleCE2_FAILED': 51,
         'ZAMS_oRLO1-contact_CC1_oRLO2_CC2_END': 50,
         'ZAMS_oCE2_CC1_CC2_END': 47,
         'ZAMS_oRLO1_CC1_oRLO2_oCE2_FAILED_FAILED': 46,
         'ZAMS_oCE2_oMerging2_FAILED_FAILED': 45,
         'ZAMS_oDoubleCE1_CC2_oRLO1_oRLO1_END': 43,
         'ZAMS_oCE1_CC1_oRLO2_maxtime_END': 41,
         'ZAMS_oRLO1-contact_CC1_oRLO2_oCE2_oMerging2_END': 40,
         'ZAMS_oDoubleCE2_CC2_CC1_END': 40,
         'ZAMS_oRLO1_CC1_oRLO2_oCE2_oCE2_oMerging2_END': 39,
         'ZAMS_oDoubleCE1_CC2_CC1_maxtime_END': 38,
         'ZAMS_CC1_FAILED_FAILED': 36,
         'ZAMS_oRLO1_CC1_FAILED_FAILED': 35,
         'ZAMS_oRLO1_CC1_oRLO2_maxtime_END': 34,
         'ZAMS_oCE1_CC1_oRLO2_CC2_FAILED': 32,
         'ZAMS_oCE1_oMerging1_maxtime_END': 24,
         'ZAMS_oCE2_CC2_END': 22,
         'ZAMS_oRLO1_CC1_oRLO2_oCE2_oCE2_FAILED_FAILED': 21,
         'ZAMS_oCE2_CC2_oRLO1_oCE1_oMerging1_END': 20,
         'ZAMS_oCE1_CC1_FAILED_FAILED': 18,
         'ZAMS_oCE1_CC1_oRLO2_FAILED_FAILED': 18,
         'ZAMS_oRLO1_CC1_oRLO2_CC2_FAILED': 18,
         'ZAMS_CC1_oRLO2_oCE2_CC2_END': 18,
         'ZAMS_oRLO1-reverse_CC1_oRLO2_oCE2_CC2_END': 17,
         'ZAMS_oDoubleCE2_oMerging2_FAILED_FAILED': 16,
         'ZAMS_oRLO1-reverse_CC1_oRLO2_oRLO2_END': 14,
         'ZAMS_oDoubleCE1_CC2_END': 12,
         'ZAMS_oRLO1-reverse_FAILED': 12,
         'ZAMS_CC1_oRLO2_oCE2_CC2_maxtime_END': 12,
         'ZAMS_oRLO1-contact_CC1_FAILED_FAILED': 11,
         'ZAMS_oRLO1_CC1_oRLO2_oRLO2_END': 11,
         'ZAMS_oRLO1_CC1_oRLO2_oCE2_CC2_FAILED_FAILED': 7,
         'ZAMS_oCE2_FAILED': 7,
         'ZAMS_oRLO1-reverse_maxtime_END': 7,
         'ZAMS_oCE2_CC1_CC2_maxtime_END': 7,
         'ZAMS_oDoubleCE1_oRLO1_FAILED_FAILED': 6,
         'ZAMS_oDoubleCE2_oRLO1-contact_FAILED_FAILED': 6,
         'ZAMS_oRLO1-reverse_CC1_oRLO2_oCE2_END': 5,
         'ZAMS_oRLO1-reverse_CC1_oRLO2_oCE2_CC2_maxtime_END': 5,
         'ZAMS_oDoubleCE2_CC2_oRLO1_CC1_END': 5,
         'ZAMS_oCE2_oRLO2_FAILED_FAILED': 4,
         'ZAMS_oCE1_CC1_oRLO2_oRLO2_END': 4,
         'ZAMS_oCE2_CC2_oRLO1_CC1_maxtime_END': 4,
         'ZAMS_oRLO1_CC1_oRLO2_END': 3,
         'ZAMS_oCE2_CC1_oRLO2_CC2_END': 3,
         'ZAMS_oRLO1_CC1_oRLO2_FAILED_FAILED': 3,
         'ZAMS_oCE1_oRLO1_FAILED': 2,
         'ZAMS_oDoubleCE2_oRLO2_FAILED_FAILED': 2,
         'ZAMS_CC1_oRLO2_oRLO2_END': 2,
         'ZAMS_oRLO1_CC1_oRLO2_CC2_FAILED_FAILED': 2,
         'ZAMS_oCE1_CC1_oRLO2_oCE2_CC2_END': 2,
         'ZAMS_oDoubleCE2_CC1_oRLO2_oRLO2_END': 2,
         'ZAMS_CC1_oRLO2_maxtime_END': 2,
         'ZAMS_oDoubleCE2_CC2_oRLO1_oRLO1_END': 1,
         'ZAMS_CC1_oRLO2_END': 1,
         'ZAMS_oRLO1-reverse_CC1_oRLO2_maxtime_END': 1,
         'ZAMS_CC1_oRLO2_CC2_FAILED_FAILED': 1,
         'ZAMS_CC1_oRLO2_oRLO2_oRLO2_oRLO2_oRLO2_oRLO2_oRLO2_oRLO2_oRLO2_oRLO2_oRLO2_oRLO2_oRLO2_oRLO2_oRLO2_o': 1,
         'ZAMS_oCE1_CC2_CC1_maxtime_END': 1,
         'ZAMS_oDoubleCE1_CC1_oRLO2_oRLO2_END': 1,
         'ZAMS_oRLO1-reverse_CC1_CC2_FAILED_FAILED': 1,
         'ZAMS_oDoubleCE1_oRLO2_FAILED_FAILED': 1,
         'ZAMS_oDoubleCE2_CC1_CC2_FAILED_FAILED': 1})

In [ ]:
fc = pop.formation_channels

mask = fc['channel'] == 'ZAMS_oCE1_oMerging1_CC1_END'

binary_indices= fc[mask].index.tolist()

In [ ]:
pop.history[binary_indices][cols]

,time,step_names,state,event,S1_state,S2_state,S1_mass,S2_mass,orbital_period
binary_index,,,,,,,,,
11,1.127619e+10,initial_cond,detached,ZAMS,H-rich_Core_H_burning,H-rich_Core_H_burning,17.031616,2.278776,7.882748
11,1.128775e+10,step_HMS_HMS,RLO1,oCE1,H-rich_Core_H_burning,H-rich_Core_H_burning,15.399892,2.308917,3.660178
11,1.128775e+10,step_CE,merged,oMerging1,H-rich_Core_H_burning,H-rich_Core_H_burning,15.399892,2.308917,3.660178
11,1.128950e+10,step_merged,merged,CC1,H-rich_Core_C_depleted,massless_remnant,9.116392,0.000000,NaN
11,1.128950e+10,step_SN,merged,NaN,BH,massless_remnant,2.804742,0.000000,NaN
...,...,...,...,...,...,...,...,...,...
999993,5.693361e+09,step_HMS_HMS,RLO1,oCE1,H-rich_Shell_H_burning,H-rich_Core_H_burning,14.951426,5.197080,120.051245
999993,5.693361e+09,step_CE,merged,oMerging1,H-rich_Shell_H_burning,H-rich_Core_H_burning,14.951426,5.197080,120.051245
999993,5.694012e+09,step_merged,merged,CC1,H-rich_Core_C_depleted,massless_remnant,10.601458,0.000000,NaN
999993,5.694012e+09,step_SN,merged,NaN,BH,massless_remnant,6.722159,0.000000,NaN
999993,5.694012e+09,step_end,merged,END,BH,massless_remnant,6.722159,0.000000,NaN

In [ ]:
merged = pop.oneline.select("state_f == merged")

In [ ]:
pop.export_selection(merged.index.to_list(), 'test.h5')