In [1]:
import pandas as pd
from pathlib import Path

# from posydon.popsyn.binarypopulation import BinaryPopulation
# from posydon.binary_evol.binarystar import BinaryStar
# from posydon.binary_evol.singlestar import SingleStar
from posydon.popsyn.synthetic_population import Population
# from posydon.popsyn.synthetic_population import PopulationRunner
# import astropy.units as u

# import os
# import shutil
# from posydon.config import PATH_TO_POSYDON

# from POSYDONHRDiagramModule import HR_Diagram
# import matplotlib.pyplot as plt
# import random as rand 

from collections import Counter

DataPath = Path().resolve().parent / 'Data'

In [2]:
cols = ['time', 'step_names', 'state', 'event', 'S1_state', 'S2_state', 'S1_mass', 'S2_mass', 'orbital_period', 'S1_log_R']
finCols = [
    'orbital_period_f',
    'eccentricity_f',
    'state_f',

    'S1_state_f',
    'S2_state_f',
    
    'S2_mass_f',
    'S2_log_R_f',
    'S2_log_L_f',


    'S1_mass_f',
    'S1_log_R_f',
    'S1_log_L_f'

 ]

initCols = [
    'orbital_period_i',
    'eccentricity_i',
    'state_i',

    'S2_state_i',
    'S2_mass_i',
    'S2_log_R_i',

    'S1_state_i',
    'S1_mass_i',
    'S1_log_R_i'
 ]

In [3]:
pop = Population('/home/bku2126/b1095/bku2126/stellarBHs/Data/1e+00_Zsun_population.h5')

In [ ]:
pop.ini_params

{'metallicity': 1.0,
 'number_of_binaries': 1000000,
 'binary_fraction_scheme': 'const',
 'binary_fraction_const': 1.0,
 'star_formation': 'constant',
 'max_simulation_time': 13800000000.0,
 'primary_mass_scheme': 'Kroupa2001',
 'primary_mass_min': 4,
 'primary_mass_max': 150.0,
 'secondary_mass_scheme': 'Moe+17-PsandQs',
 'secondary_mass_min': 0.1,
 'secondary_mass_max': 150.0,
 'orbital_scheme': 'period',
 'orbital_period_scheme': 'Moe+17-PsandQs',
 'orbital_period_min': 0.75,
 'orbital_period_max': 6000.0,
 'orbital_separation_scheme': 'log_uniform',
 'orbital_separation_min': 5.0,
 'orbital_separation_max': 100000.0,
 'eccentricity_scheme': 'zero'}

In [ ]:
len(pop)

1000000

In [6]:
df = pop.history.select()
dfOneline = pop.oneline.select()

In [7]:
df.loc[199300][cols]

,time,step_names,state,event,S1_state,S2_state,S1_mass,S2_mass,orbital_period,S1_log_R
binary_index,,,,,,,,,,
199300,4.980953e+09,initial_cond,detached,ZAMS,H-rich_Core_H_burning,H-rich_Core_H_burning,14.334016,2.575489,3037.125988,0.000000
199300,4.996101e+09,step_HMS_HMS,RLO1,oCE1,H-rich_Core_He_depleted,H-rich_Core_H_burning,12.290008,2.595393,1897.398040,2.972926
199300,4.996101e+09,step_CE,detached,NaN,stripped_He_Core_He_depleted,H-rich_Core_H_burning,4.903492,2.595393,1.387402,-0.439940
199300,4.996114e+09,step_detached,detached,CC1,stripped_He_Core_C_depleted,H-rich_Core_H_burning,4.899383,2.909990,1.369550,0.094807
199300,4.996114e+09,step_SN,detached,NaN,NS,H-rich_Core_H_burning,1.671411,2.909990,34.070532,-4.745687
199300,5.290889e+09,step_detached,RLO2,oRLO2,NS,H-rich_Core_H_burning,1.671411,2.901292,1.373602,-4.745687
199300,7.081756e+09,step_CO_HMS_RLO,detached,CC2,BH,H-rich_Core_H_burning,2.785568,0.091402,3.097021,-4.927212
199300,7.081756e+09,,ERR,FAILED,BH,H-rich_Core_H_burning,2.785568,0.091402,3.097021,-4.927212

In [8]:
dfOneline[initCols].describe()

,orbital_period_i,eccentricity_i,S2_mass_i,S2_log_R_i,S1_mass_i,S1_log_R_i
count,633340.000000,633340.0,1000000.000000,633340.0,1000000.000000,1000000.0
mean,660.069380,0.0,4.216327,0.0,11.618591,0.0
std,1221.202401,0.0,8.697919,0.0,14.702374,0.0
min,0.750001,0.0,0.000000,0.0,4.000001,0.0
25%,7.300385,0.0,0.000000,0.0,4.980537,0.0
50%,70.292423,0.0,1.690187,0.0,6.778029,0.0
75%,653.408100,0.0,4.557395,0.0,11.405791,0.0
max,5999.956810,0.0,148.877088,0.0,149.975532,0.0

In [9]:
df.S2_state.value_counts()

S2_state
massless_remnant                2096543
H-rich_Core_H_burning           2058166
WD                               306724
NS                               189103
H-rich_Core_He_depleted          181676
H-rich_Shell_H_burning           174230
BH                               116035
H-rich_Core_C_depleted           114701
stripped_He_Core_C_depleted       43336
stripped_He_Core_He_depleted      31163
H-rich_Core_He_burning            16979
stripped_He_non_burning           15850
stripped_He_Core_He_burning        8411
H-rich_non_burning                 3180
accreted_He_non_burning             648
accreted_He_Core_He_burning         319
accreted_He_Core_H_burning           76
accreted_He_Shell_H_burning          22
stripped_He_Shell_H_burning           2
Name: count, dtype: int64

In [10]:
sol_bhMaskMWdur = ((
    ((df['S1_state'] == 'BH') & (df['S2_state'] == 'H-rich_Core_H_burning'))
    )   & (df['event'] != 'END')
        & (df['state'] == 'detached')
)

In [11]:
filtered_df = df[sol_bhMaskMWdur]

In [26]:
10e9

10000000000.0

In [ ]:
filtered_df[filtered_df['S2_mass'] < 2.3][cols]

,time,step_names,state,event,S1_state,S2_state,S1_mass,S2_mass,orbital_period,S1_log_R
binary_index,,,,,,,,,,
6172,1.581094e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,2.751273,1.916033,15950.270637,-4.932592
68561,3.691715e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,3.747350,1.911536,1.849214,-4.798401
68561,1.336309e+10,step_CO_HMS_RLO,detached,CC2,BH,H-rich_Core_H_burning,5.403750,0.128428,11.224325,-4.639430
86804,1.077803e+10,step_CO_HMS_RLO,detached,CC2,BH,H-rich_Core_H_burning,3.282722,0.355433,11.297345,-4.855891
106547,1.242505e+10,step_CO_HMS_RLO,detached,CC2,BH,H-rich_Core_H_burning,3.268237,0.148342,12.704747,-4.857812
198138,7.969938e+09,step_CO_HMS_RLO,detached,CC2,BH,H-rich_Core_H_burning,3.763195,0.428597,13.715771,-4.796569
199300,7.081756e+09,step_CO_HMS_RLO,detached,CC2,BH,H-rich_Core_H_burning,2.785568,0.091402,3.097021,-4.927212
267277,1.224405e+10,step_CO_HMS_RLO,detached,CC2,BH,H-rich_Core_H_burning,3.503672,0.296857,7.713232,-4.827602
357232,1.380000e+10,NaN,detached,maxtime,BH,H-rich_Core_H_burning,2.690295,0.021281,0.046032,-4.942325
377396,1.197593e+10,step_SN,detached,NaN,BH,H-rich_Core_H_burning,2.780802,2.266250,1075.896086,-4.927955
402228,8.448889e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,3.136513,1.793448,8.204241,-4.875678
495833,5.462662e+09,step_CO_HMS_RLO,detached,CC2,BH,H-rich_Core_H_burning,2.543167,0.084394,2.159860,-4.966750
563444,2.652308e+09,step_CO_HMS_RLO,detached,CC2,BH,H-rich_Core_H_burning,2.645931,0.199414,10.347254,-4.949547
801466,9.792912e+09,step_CO_HMS_RLO,detached,CC2,BH,H-rich_Core_H_burning,3.472458,0.280163,8.962438,-4.831488
839107,5.565634e+09,step_CO_HMS_RLO,detached,CC2,BH,H-rich_Core_H_burning,2.614052,0.232999,11.361084,-4.954811
856080,1.111433e+10,step_CO_HMS_RLO,detached,CC2,BH,H-rich_Core_H_burning,2.753565,0.211229,4.612772,-4.932230
863874,5.563134e+09,step_CO_HMS_RLO,detached,CC2,BH,H-rich_Core_H_burning,3.011468,0.262993,9.397414,-4.893347
893211,8.068772e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,4.664751,2.208363,0.459428,-4.703297
982287,2.239707e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,3.630861,1.962480,24.633727,-4.812116

In [13]:
df[
    (df['S1_state'] == 'BH') & (df['S2_state'] == 'H-rich_Core_H_burning')
    &  (df['state'] == 'detached')
    &  (df['S2_mass'] < 3) & (df['orbital_period'] < 3.5)
    &  (df['S2_mass'] > .1)
    &  (df['time'] < 10e9)
    ][cols]

,time,step_names,state,event,S1_state,S2_state,S1_mass,S2_mass,orbital_period,S1_log_R
binary_index,,,,,,,,,,
68561,3.691715e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,3.747350,1.911536,1.849214,-4.798401
403504,6.781736e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,3.842919,2.819491,2.973241,-4.787464
410679,2.657450e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,3.746921,2.586967,3.436552,-4.798451
563655,9.633998e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,4.352769,2.491193,2.778295,-4.733360
893211,8.068772e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,4.664751,2.208363,0.459428,-4.703297
954453,5.513595e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,4.495786,2.838026,2.684976,-4.719320

In [14]:
dfOneline

,state_i,event_i,time_i,separation_i,orbital_period_i,eccentricity_i,rl_relative_overflow_1_i,rl_relative_overflow_2_i,lg_mtransfer_rate_i,step_names_i,...,interp_class_CO_HMS_RLO,interp_class_CO_HeMS,interp_class_CO_HeMS_RLO,mt_history_HMS_HMS,mt_history_CO_HMS_RLO,mt_history_CO_HeMS,mt_history_CO_HeMS_RLO,FAILED,WARNING,metallicity
binary_index,,,,,,,,,,,,,,,,,,,,,
0,detached,ZAMS,8.285364e+09,23.122776,4.028920,0.0,NaN,NaN,NaN,initial_cond,...,NaN,NaN,NaN,Last stable RLOF during stripped He star,NaN,NaN,NaN,1,0,1.0
1,initially_single_star,ZAMS,8.375018e+09,NaN,NaN,NaN,NaN,NaN,NaN,initial_cond,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,1,1.0
2,detached,ZAMS,1.001787e+10,194.470562,111.655153,0.0,NaN,NaN,NaN,initial_cond,...,NaN,NaN,NaN,Unstable RLOF during postMS,NaN,NaN,NaN,0,1,1.0
3,detached,ZAMS,1.157759e+10,62.015099,17.730334,0.0,NaN,NaN,NaN,initial_cond,...,unstable_MT,no_MT,NaN,Last stable RLOF during stripped He star,Unstable RLOF during postMS,no RLOF,NaN,0,0,1.0
4,initially_single_star,ZAMS,3.714239e+09,NaN,NaN,NaN,NaN,NaN,NaN,initial_cond,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,1,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,initially_single_star,ZAMS,5.620251e+09,NaN,NaN,NaN,NaN,NaN,NaN,initial_cond,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,1,1.0
999996,initially_single_star,ZAMS,1.324138e+10,NaN,NaN,NaN,NaN,NaN,NaN,initial_cond,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,1,1.0
999997,detached,ZAMS,9.075695e+09,367.088602,289.345230,0.0,NaN,NaN,NaN,initial_cond,...,NaN,NaN,NaN,Unstable RLOF during postMS,NaN,NaN,NaN,0,1,1.0
999998,initially_single_star,ZAMS,2.114737e+09,NaN,NaN,NaN,NaN,NaN,NaN,initial_cond,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,1,1.0
999999,detached,ZAMS,1.293519e+10,661.754383,599.008784,0.0,NaN,NaN,NaN,initial_cond,...,NaN,NaN,NaN,Unstable RLOF during postMS,NaN,NaN,NaN,1,1,1.0

In [15]:
sol_bhInitMask = (
    ((df['S1_state'] == 'BH') & (df['S2_state'] == 'H-rich_Core_H_burning'))
    # ((df['S2_state'] == 'BH') & (df['S1_state'] == 'H-rich_Core_H_burning'))
) &  (df['state'] == 'detached')


sol_bhMaskNext = sol_bhInitMask.groupby(level=0).shift(1, fill_value=False)

sol_bhMask = sol_bhInitMask | sol_bhMaskNext

specStatedf = df[sol_bhMask] ### makes a df with the row with the sol-bh and the row after. used for finding the lifespan of the systems 

sol_bhMaskFirst = pd.Series(False, index = sol_bhMask.index)
sol_bhMaskFirst = ~sol_bhMaskFirst.index.duplicated(keep='first')

firstAndsol_bh = sol_bhInitMask | sol_bhMaskFirst
### makes a mask with the init cond and the row with the bh-sol, not super useful when compared to just using bh-ms row df + oneline 

def isMW(group): ### this is wayyyyy too narrow of a process... it does work though!
    return (group['time'].iloc[0] < 10e9) & (group['time'].iloc[1] > 10e9)
TenGyr = df[sol_bhMask].groupby(level=0).apply(isMW)

def isMW2(group): ### this is wayyyyy too narrow of a process... it does work though!
    return (group['time'].iloc[0] < 10e9) & (group['time'].iloc[-1] > 10e9)
FullDFTenGyrMask = df.groupby(level=0).apply(isMW2)
def findStatDur(group):
        return (group['time'].iloc[1] - group['time'].iloc[0])

In [16]:
df[sol_bhInitMask][cols]

,time,step_names,state,event,S1_state,S2_state,S1_mass,S2_mass,orbital_period,S1_log_R
binary_index,,,,,,,,,,
34,1.354658e+10,step_SN,detached,NaN,BH,H-rich_Core_H_burning,11.742339,20.766340,773.934254,-4.302371
40,9.365578e+08,step_SN,detached,NaN,BH,H-rich_Core_H_burning,2.862360,27.696843,13.464326,-4.915401
66,7.320985e+08,step_SN,detached,NaN,BH,H-rich_Core_H_burning,14.104784,42.583776,42.991418,-4.222759
83,4.982609e+08,step_SN,detached,NaN,BH,H-rich_Core_H_burning,4.339844,11.088933,10.559919,-4.734651
86,1.001154e+10,step_SN,detached,NaN,BH,H-rich_Core_H_burning,12.474239,37.183199,38.437130,-4.276111
...,...,...,...,...,...,...,...,...,...,...
999858,8.317989e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,11.144016,17.054852,10.937788,-4.325084
999861,1.068474e+10,step_SN,detached,NaN,BH,H-rich_Core_H_burning,17.090943,11.066489,573.468964,-4.139359
999931,9.064239e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,3.570469,12.382211,18964.253312,-4.819400
999940,9.362281e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,3.746892,9.131854,0.941797,-4.798454
999944,5.691558e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,13.275789,32.924976,3998.959992,-4.249065

In [17]:
df[FullDFTenGyrMask].index.nunique()

/tmp/ipykernel_3618552/448617935.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.

67102

In [18]:
df[FullDFTenGyrMask]

/tmp/ipykernel_3618552/243315231.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.

,state,event,time,separation,orbital_period,eccentricity,rl_relative_overflow_1,rl_relative_overflow_2,lg_mtransfer_rate,step_names,...,S2_conv_env_turnover_time_l_b,S2_conv_env_turnover_time_l_t,S2_envelope_binding_energy,S2_mass_conv_reg_fortides,S2_thickness_conv_reg_fortides,S2_radius_conv_reg_fortides,S2_lambda_CE_1cent,S2_lambda_CE_10cent,S2_lambda_CE_30cent,S2_lambda_CE_pure_He_star_10cent
binary_index,,,,,,,,,,,,,,,,,,,,,
10,detached,ZAMS,1.264866e+09,1611.272557,2853.758189,0.0,NaN,NaN,NaN,initial_cond,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,detached,CC1,1.379082e+09,2966.758024,9980.704585,0.0,-0.921184,-0.998619,-90.532387,step_HMS_HMS,...,0.0,-6.624153e+98,-8.858761e+48,0.010759,0.013329,1.389870,1.009376e+00,1.009376e+00,1.009376e+00,1.010305
10,detached,NaN,1.379082e+09,3736.636100,15835.171890,0.0,NaN,NaN,NaN,step_SN,...,0.0,-6.624153e+98,-8.858761e+48,0.010759,0.013329,1.389870,1.009376e+00,1.009376e+00,1.009376e+00,1.010305
10,detached,CC2,2.674916e+09,8536.563219,74274.061027,0.0,-1.000000,-0.999994,NaN,step_detached,...,0.0,0.000000e+00,-1.038202e+46,0.000000,0.000000,0.000000,6.194448e+98,6.194448e+98,6.194448e+98,1.904796
10,detached,NaN,2.674916e+09,8656.689104,76379.126885,0.0,NaN,NaN,NaN,step_SN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999985,detached,NaN,4.227278e+09,5221.395761,30377.875136,0.0,NaN,NaN,NaN,step_SN,...,0.0,0.000000e+00,-3.927159e+48,0.005838,0.107979,0.802218,1.196278e+00,1.199644e+00,1.196278e+00,1.196278
999985,detached,CC2,1.034905e+10,7465.626572,62152.163007,0.0,-1.000000,-0.999993,NaN,step_detached,...,0.0,0.000000e+00,-3.376127e+46,0.000000,0.000000,0.000000,8.612397e-01,8.674992e-01,8.728985e-01,1.753510
999985,detached,NaN,1.034905e+10,7644.537644,65166.765977,0.0,NaN,NaN,NaN,step_SN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
999985,detached,maxtime,1.380000e+10,7644.537644,65166.765977,0.0,-1.000000,-1.000000,NaN,step_dco,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
999985,detached,END,1.380000e+10,7644.537644,65166.765977,0.0,-1.000000,-1.000000,NaN,step_end,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [19]:
solBhs = df[sol_bhMask]
SolBH10Gyr = solBhs[TenGyr]

detachedState = SolBH10Gyr[SolBH10Gyr['step_names'] == 'step_SN']

/tmp/ipykernel_3618552/2669472495.py:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.

In [20]:
detachedState[cols]

,time,step_names,state,event,S1_state,S2_state,S1_mass,S2_mass,orbital_period,S1_log_R
binary_index,,,,,,,,,,
115941,9.972059e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,3.091624,7.537212,3.644188,-4.881939
162444,9.998314e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,2.908801,12.660248,672.279756,-4.908411
166117,9.993887e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,16.965615,18.407261,31.123508,-4.142556
282843,9.991966e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,19.448029,9.210774,1405.281610,-4.083250
303421,9.995698e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,12.198113,8.300179,181430.861936,-4.285833
326549,9.989270e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,23.592582,14.951399,9959.056674,-3.999350
341400,9.997352e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,2.943107,14.358771,301.044267,-4.903319
407686,9.607671e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,8.219198,3.062020,12870.165715,-4.457296
454861,9.823368e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,12.323838,4.040776,20338.118796,-4.281379
503621,9.839274e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,12.800980,3.553614,38922.735348,-4.264882
517348,9.993529e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,3.071852,7.913187,12.967199,-4.884725
563655,9.633998e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,4.352769,2.491193,2.778295,-4.733360
613202,9.983104e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,20.162413,7.895929,1794.640372,-4.067583
643508,9.993437e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,12.582534,11.190474,2681.228806,-4.272357
706977,9.984346e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,14.158589,8.609096,47.498163,-4.221105
728195,9.959058e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,12.096233,7.495170,36.465526,-4.289475
746845,9.984231e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,9.165623,8.413085,54.914868,-4.409963
819526,9.988061e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,13.924864,12.624693,37872.557699,-4.228334
870495,9.995758e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,12.685769,16.822873,1388.161257,-4.268808
886786,9.995723e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,12.999065,11.843004,870.344023,-4.258213
895592,9.868859e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,3.493515,3.406378,23818.370124,-4.828863
912534,9.999157e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,3.426813,10.814838,20.198982,-4.837235
946917,9.997892e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,13.360833,10.005710,2988.515309,-4.246292
966537,9.995129e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,12.300525,10.774756,478.618033,-4.282202
972055,9.982113e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,6.896362,9.848378,35.706447,-4.533505
973736,9.989924e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,3.709383,10.048431,16.344035,-4.802824

In [21]:
detachedState[detachedState['S2_mass'] < 2.3][cols]

Empty DataFrame
Columns: [time, step_names, state, event, S1_state, S2_state, S1_mass, S2_mass, orbital_period, S1_log_R]
Index: []

In [22]:
filtered_df[(filtered_df['S2_mass'] < 2.5) & (filtered_df['orbital_period'] < 3.5) & (filtered_df['time'] <10e9)][cols]

,time,step_names,state,event,S1_state,S2_state,S1_mass,S2_mass,orbital_period,S1_log_R
binary_index,,,,,,,,,,
68561,3.691715e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,3.747350,1.911536,1.849214,-4.798401
199300,7.081756e+09,step_CO_HMS_RLO,detached,CC2,BH,H-rich_Core_H_burning,2.785568,0.091402,3.097021,-4.927212
495833,5.462662e+09,step_CO_HMS_RLO,detached,CC2,BH,H-rich_Core_H_burning,2.543167,0.084394,2.159860,-4.966750
563655,9.633998e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,4.352769,2.491193,2.778295,-4.733360
893211,8.068772e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,4.664751,2.208363,0.459428,-4.703297

In [ ]:
df.loc[34222][cols]

,time,step_names,state,event,S1_state,S2_state,S1_mass,S2_mass,orbital_period
binary_index,,,,,,,,,
34222,7.816161e+09,initial_cond,detached,ZAMS,H-rich_Core_H_burning,H-rich_Core_H_burning,18.488846,6.041695,673.205977
34222,7.826776e+09,step_HMS_HMS,RLO1,oCE1,H-rich_Shell_H_burning,H-rich_Core_H_burning,11.651054,6.150812,252.112118
34222,7.826776e+09,step_CE,detached,NaN,stripped_He_non_burning,H-rich_Core_H_burning,6.518232,6.117600,0.887240
34222,7.826784e+09,step_detached,detached,CC1,stripped_He_Core_C_depleted,H-rich_Core_H_burning,6.493311,6.117590,0.900957
34222,7.826784e+09,step_SN,detached,NaN,NS,H-rich_Core_H_burning,2.493044,6.117590,3.532180
34222,7.853264e+09,step_detached,RLO2,oRLO2,NS,H-rich_Core_H_burning,2.493044,6.111617,1.026671
34222,7.863070e+09,step_CO_HMS_RLO,RLO2,oCE2,BH,H-rich_Core_H_burning,3.329968,0.704356,0.183356
34222,7.863070e+09,step_CE,merged,oMerging2,BH,H-rich_Core_H_burning,3.329968,0.704356,0.183356
34222,1.380000e+10,step_merged,merged,NaN,BH,massless_remnant,3.329968,0.000000,NaN
34222,1.380000e+10,step_end,merged,END,BH,massless_remnant,3.329968,0.000000,NaN