In [48]:
import pandas as pd
from pathlib import Path

# from posydon.popsyn.binarypopulation import BinaryPopulation
# from posydon.binary_evol.binarystar import BinaryStar
# from posydon.binary_evol.singlestar import SingleStar
from posydon.popsyn.synthetic_population import Population
# from posydon.popsyn.synthetic_population import PopulationRunner
# import astropy.units as u

# import os
# import shutil
# from posydon.config import PATH_TO_POSYDON

# from POSYDONHRDiagramModule import HR_Diagram
# import matplotlib.pyplot as plt
# import random as rand 

from collections import Counter

DataPath = Path().resolve().parent / 'Data'

In [49]:
cols = ['time', 'step_names', 'state', 'event', 'S1_state', 'S2_state', 'S1_mass', 'S2_mass', 'orbital_period']
finCols = [
    'orbital_period_f',
    'eccentricity_f',
    'state_f',

    'S1_state_f',
    'S2_state_f',
    
    'S2_mass_f',
    'S2_log_R_f',
    'S2_log_L_f',


    'S1_mass_f',
    'S1_log_R_f',
    'S1_log_L_f'

 ]

initCols = [
    'orbital_period_i',
    'eccentricity_i',
    'state_i',

    'S2_state_i',
    'S2_mass_i',
    'S2_log_R_i',

    'S1_state_i',
    'S1_mass_i',
    'S1_log_R_i'
 ]

In [50]:
pop = Population(str(DataPath / 'bhSolSubpop.h5'))

In [51]:
len(pop)

41191

In [52]:
pop.calculate_formation_channels()

In [53]:
Counter(pop.formation_channels['channel'])

Counter({'ZAMS_oRLO1_CC1_oRLO2_CC2_END': 14627,
         'ZAMS_oRLO1_CC1_oRLO2_CC2_maxtime_END': 8016,
         'ZAMS_CC1_oRLO2_CC2_maxtime_END': 4146,
         'ZAMS_CC1_oRLO2_CC2_END': 4133,
         'ZAMS_oRLO1_CC1_oRLO2_oCE2_oMerging2_END': 3180,
         'ZAMS_oRLO1_CC1_END': 1327,
         'ZAMS_CC1_CC2_END': 1180,
         'ZAMS_oRLO1_CC1_oRLO2_oCE2_CC2_END': 1092,
         'ZAMS_CC1_CC2_maxtime_END': 815,
         'ZAMS_CC1_oRLO2_oCE2_oMerging2_END': 413,
         'ZAMS_oRLO1_CC1_oRLO2_oCE2_CC2_maxtime_END': 338,
         'ZAMS_oCE1_CC1_oRLO2_CC2_maxtime_END': 279,
         'ZAMS_oRLO1-contact_CC1_oRLO2_oCE2_oMerging2_END': 268,
         'ZAMS_oRLO1_CC1_oRLO2_oCE2_END': 243,
         'ZAMS_oRLO1_CC1_CC2_END': 191,
         'ZAMS_oRLO1-contact_CC1_END': 158,
         'ZAMS_oRLO1_CC1_CC2_maxtime_END': 122,
         'ZAMS_oCE1_CC1_END': 99,
         'ZAMS_CC1_END': 95,
         'ZAMS_oCE1_CC1_oRLO2_oCE2_oMerging2_END': 90,
         'ZAMS_oCE1_CC1_oRLO2_CC2_END': 59,
         'ZAMS_oRLO1_CC1_maxtime_END': 51,
         'ZAMS_oRLO1-reverse_CC1_END': 44,
         'ZAMS_oRLO1-contact_CC1_oRLO2_CC2_maxtime_END': 37,
         'ZAMS_oRLO1-reverse_CC1_oRLO2_CC2_maxtime_END': 33,
         'ZAMS_oRLO1-contact_CC1_oRLO2_CC2_END': 31,
         'ZAMS_CC1_oRLO2_oCE2_CC2_maxtime_END': 31,
         'ZAMS_oRLO1-reverse_CC1_oRLO2_CC2_END': 20,
         'ZAMS_oRLO1-reverse_CC1_oRLO2_oCE2_oMerging2_END': 20,
         'ZAMS_CC1_maxtime_END': 15,
         'ZAMS_oCE1_CC1_oRLO2_CC2_FAILED': 14,
         'ZAMS_oRLO1-contact_CC1_CC2_maxtime_END': 12,
         'ZAMS_oCE1_CC1_maxtime_END': 12,
         'ZAMS_oRLO1-reverse_CC1_CC2_maxtime_END': 10,
         'ZAMS_oRLO1_CC1_oRLO2_oCE2_oCE2_oMerging2_END': 9,
         'ZAMS_CC1_oRLO2_oCE2_CC2_END': 7,
         'ZAMS_oCE1_CC1_CC2_maxtime_END': 5,
         'ZAMS_oCE1_CC1_oRLO2_maxtime_END': 5,
         'ZAMS_oRLO1_CC1_oRLO2_maxtime_END': 4,
         'ZAMS_oRLO1_CC1_FAILED_FAILED': 4,
         'ZAMS_CC1_FAILED_FAILED': 4,
         'ZAMS_oRLO1_CC1_oRLO2_oCE2_CC2_FAILED_FAILED': 3,
         'ZAMS_oRLO1-reverse_CC1_CC2_END': 2,
         'ZAMS_oRLO1_CC1_oRLO2_CC2_FAILED': 1,
         'ZAMS_CC1_oRLO2_END': 1,
         'ZAMS_oRLO1-reverse_CC1_oRLO2_oCE2_END': 1})

In [54]:
solBH_oneline_df = pop.oneline.select()
solBH_history_df = pop.history.select()

In [73]:
solBH_oneline_df

,state_i,event_i,time_i,separation_i,orbital_period_i,eccentricity_i,rl_relative_overflow_1_i,rl_relative_overflow_2_i,lg_mtransfer_rate_i,step_names_i,...,interp_class_CO_HMS_RLO,interp_class_CO_HeMS,interp_class_CO_HeMS_RLO,mt_history_HMS_HMS,mt_history_CO_HMS_RLO,mt_history_CO_HeMS,mt_history_CO_HeMS_RLO,FAILED,WARNING,metallicity
binary_index,,,,,,,,,,,,,,,,,,,,,
0,detached,ZAMS,1.354058e+10,314.927115,86.368549,0.0,NaN,NaN,NaN,initial_cond,...,stable_MT,NaN,NaN,Last stable RLOF during postMS,Last stable RLOF during postMS,NaN,NaN,0,0,1.0
1,detached,ZAMS,9.269310e+08,42.893063,4.949364,0.0,NaN,NaN,NaN,initial_cond,...,NaN,NaN,NaN,Stable contact phase,NaN,NaN,NaN,0,1,1.0
2,detached,ZAMS,7.282359e+08,83.936347,7.613953,0.0,NaN,NaN,NaN,initial_cond,...,stable_MT,NaN,NaN,no RLOF,Last stable RLOF during postMS,NaN,NaN,0,0,1.0
3,detached,ZAMS,4.896616e+08,346.312644,129.999715,0.0,NaN,NaN,NaN,initial_cond,...,stable_MT,NaN,NaN,Unstable RLOF during postMS,Last stable RLOF during stripped He star,NaN,NaN,0,1,1.0
4,detached,ZAMS,1.000807e+10,77.296905,6.337424,0.0,NaN,NaN,NaN,initial_cond,...,stable_MT,NaN,NaN,no RLOF,Last stable RLOF during postMS,NaN,NaN,0,0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41242,detached,ZAMS,8.312676e+09,79.470260,10.689626,0.0,NaN,NaN,NaN,initial_cond,...,stable_MT,NaN,NaN,Last stable RLOF during postMS,Last stable RLOF during postMS,NaN,NaN,0,0,1.0
41243,detached,ZAMS,1.067994e+10,792.218696,331.835337,0.0,NaN,NaN,NaN,initial_cond,...,stable_MT,NaN,NaN,no RLOF,Last stable RLOF during postMS,NaN,NaN,0,0,1.0
41244,detached,ZAMS,9.054567e+09,285.509574,96.941221,0.0,NaN,NaN,NaN,initial_cond,...,stable_MT,NaN,NaN,Last stable RLOF during postMS,Last stable RLOF during postMS,NaN,NaN,0,0,1.0
41245,detached,ZAMS,9.352825e+09,372.819841,154.288032,0.0,NaN,NaN,NaN,initial_cond,...,NaN,NaN,NaN,Unstable RLOF during postMS,NaN,NaN,NaN,0,1,1.0
41246,detached,ZAMS,5.687928e+09,286.403130,49.544310,0.0,NaN,NaN,NaN,initial_cond,...,stable_MT,NaN,NaN,no RLOF,Last stable RLOF during postMS,NaN,NaN,0,0,1.0

In [55]:
sol_bhInitMask = (
    ((solBH_history_df['S1_state'] == 'BH') & (solBH_history_df['S2_state'] == 'H-rich_Core_H_burning')) |
    ((solBH_history_df['S2_state'] == 'BH') & (solBH_history_df['S1_state'] == 'H-rich_Core_H_burning'))
) & (solBH_history_df['event'] != 'END')

sol_bhMaskNext = sol_bhInitMask.groupby(level=0).shift(1, fill_value=False)

sol_bhMask = sol_bhInitMask | sol_bhMaskNext

specStatedf = solBH_history_df[sol_bhMask] ### makes a df with the row with the sol-bh and the row after. used for finding the lifespan of the systems 

sol_bhMaskFirst = pd.Series(False, index = sol_bhMask.index)
sol_bhMaskFirst = ~sol_bhMaskFirst.index.duplicated(keep='first')

firstAndsol_bh = sol_bhInitMask | sol_bhMaskFirst
### makes a mask with the init cond and the row with the bh-sol, not super useful when compared to just using bh-ms row df + oneline 

# def isMW(group): ### this is wayyyyy too narrow of a process... it does work though!
#     return (group['time'].iloc[0] < 10e9) & (group['time'].iloc[1] > 10e9)
# results = solBH_history_df[sol_bhMask].groupby(level=0).apply(isMW)

def findStatDur(group):
        return (group['time'].iloc[1] - group['time'].iloc[0])

In [56]:
sol_bh_lifespan_list = specStatedf.groupby(level=0).apply(findStatDur)
sol_bh_FormationTime_List = solBH_history_df[firstAndsol_bh].groupby(level=0).apply(findStatDur)

In [57]:
sol_bh_lifespan_list.describe()

count    4.119100e+04
mean     7.961639e+06
std      2.094689e+07
min      0.000000e+00
25%      1.145769e+06
50%      3.525567e+06
75%      9.046779e+06
max      1.373802e+09
dtype: float64

In [58]:
sol_bh_FormationTime_List.describe()

count    4.119100e+04
mean     6.106691e+06
std      3.651581e+07
min      3.200919e+06
25%      4.176094e+06
50%      5.230424e+06
75%      6.702036e+06
max      5.568467e+09
dtype: float64

In [59]:
tolerance = 1e9

sol_bhMaskMWdur = ((
    ((solBH_history_df['S1_state'] == 'BH') & (solBH_history_df['S2_state'] == 'H-rich_Core_H_burning')) |
    ((solBH_history_df['S2_state'] == 'BH') & (solBH_history_df['S1_state'] == 'H-rich_Core_H_burning'))
    )   & (solBH_history_df['event'] != 'END')
        & (solBH_history_df['time'] > 10e9 - tolerance)
        & (solBH_history_df['time'] < 10e9 + tolerance)
        & (solBH_history_df['state'] == 'detached')
)

In [60]:
len(solBH_history_df[sol_bhMaskMWdur])

5994

In [61]:
lowPorbSolBH = solBH_history_df[sol_bhMaskMWdur][solBH_history_df[sol_bhMaskMWdur]['orbital_period'] < 3]

In [62]:
lowPorbSolBH[cols]

,time,step_names,state,event,S1_state,S2_state,S1_mass,S2_mass,orbital_period
binary_index,,,,,,,,,
261,9.005453e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,2.720699,7.515792,2.597624
605,1.095540e+10,step_SN,detached,NaN,BH,H-rich_Core_H_burning,5.858426,11.333348,1.460274
733,1.071638e+10,step_SN,detached,NaN,BH,H-rich_Core_H_burning,3.925841,23.076179,2.895749
2120,9.467351e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,5.446302,22.059192,2.399101
2179,9.179265e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,2.578924,8.765645,2.581370
...,...,...,...,...,...,...,...,...,...
40036,9.258820e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,3.623154,7.688547,1.565752
40101,9.836158e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,4.368231,21.563922,2.993418
40899,1.066889e+10,step_SN,detached,NaN,BH,H-rich_Core_H_burning,3.637108,23.809724,2.961343
41037,1.069579e+10,step_SN,detached,NaN,BH,H-rich_Core_H_burning,3.204625,15.702403,2.474185
41245,9.362281e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,3.746892,9.131854,0.941797

In [63]:
lowPorbSolBH.to_csv(DataPath / 'threeDayPorb_solBHPairRows.csv')

In [64]:
pop.export_selection(lowPorbSolBH.index.to_list(), str(DataPath / 'bhSol_10Gyr_LowPorb_Subpop.h5'), append=False, overwrite=True)

In [65]:
FiveDPorbSolBH = solBH_history_df[sol_bhMaskMWdur][solBH_history_df[sol_bhMaskMWdur]['orbital_period'] < 5]

In [66]:
FiveDPorbSolBH[cols]

,time,step_names,state,event,S1_state,S2_state,S1_mass,S2_mass,orbital_period
binary_index,,,,,,,,,
32,1.046013e+10,step_SN,detached,NaN,BH,H-rich_Core_H_burning,9.619724,28.913699,3.789623
261,9.005453e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,2.720699,7.515792,2.597624
605,1.095540e+10,step_SN,detached,NaN,BH,H-rich_Core_H_burning,5.858426,11.333348,1.460274
733,1.071638e+10,step_SN,detached,NaN,BH,H-rich_Core_H_burning,3.925841,23.076179,2.895749
1030,1.089803e+10,step_SN,detached,NaN,BH,H-rich_Core_H_burning,2.627471,8.534797,4.370621
...,...,...,...,...,...,...,...,...,...
41037,1.069579e+10,step_SN,detached,NaN,BH,H-rich_Core_H_burning,3.204625,15.702403,2.474185
41038,1.015165e+10,step_SN,detached,NaN,BH,H-rich_Core_H_burning,3.149919,16.967927,4.037030
41093,9.813266e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,3.077906,6.586934,4.465087
41184,9.026899e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,3.347515,20.683932,4.818280
41245,9.362281e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,3.746892,9.131854,0.941797

In [67]:
FiveDPorbSolBH[FiveDPorbSolBH['S2_mass'] < 3]

,state,event,time,separation,orbital_period,eccentricity,rl_relative_overflow_1,rl_relative_overflow_2,lg_mtransfer_rate,step_names,...,S2_conv_env_turnover_time_l_b,S2_conv_env_turnover_time_l_t,S2_envelope_binding_energy,S2_mass_conv_reg_fortides,S2_thickness_conv_reg_fortides,S2_radius_conv_reg_fortides,S2_lambda_CE_1cent,S2_lambda_CE_10cent,S2_lambda_CE_30cent,S2_lambda_CE_pure_He_star_10cent
binary_index,,,,,,,,,,,,,,,,,,,,,
23416,detached,NaN,9.633998e+09,15.784547,2.778295,0.451439,NaN,NaN,NaN,step_SN,...,0.0,0.0,-1.254624e+49,1.279248e-09,0.003767,1.711091,1.083348,1.083348,1.083348,1.083348

In [68]:
pop.export_selection(FiveDPorbSolBH.index.to_list(), str(DataPath / 'bhSol_10Gyr_FiveDay_Subpop.h5'), append=False, overwrite=True)

In [69]:
filtPop = Population(str(DataPath / 'bhSol_10Gyr_LowPorb_Subpop.h5'))

In [70]:
len(filtPop)

80

In [71]:
filtPop.history.select()[cols]

,time,step_names,state,event,S1_state,S2_state,S1_mass,S2_mass,orbital_period
binary_index,,,,,,,,,
0,8.995911e+09,initial_cond,detached,ZAMS,H-rich_Core_H_burning,H-rich_Core_H_burning,21.649254,7.025360,13.252380
0,9.005453e+09,step_HMS_HMS,detached,CC1,stripped_He_Core_C_depleted,H-rich_Core_H_burning,6.748006,7.515792,2.207866
0,9.005453e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,2.720699,7.515792,2.597624
0,9.005453e+09,step_detached,initial_RLOF,NaN,BH,H-rich_Core_H_burning,2.720699,7.536774,2.597624
0,9.005453e+09,step_end,initial_RLOF,END,BH,H-rich_Core_H_burning,2.720699,7.536774,2.597624
...,...,...,...,...,...,...,...,...,...
79,9.362273e+09,step_CE,detached,NaN,stripped_He_non_burning,H-rich_Core_H_burning,7.457188,9.061668,1.493836
79,9.362281e+09,step_detached,detached,CC1,stripped_He_Core_He_depleted,H-rich_Core_H_burning,7.396282,9.131854,1.514407
79,9.362281e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,3.746892,9.131854,0.941797
79,9.362281e+09,step_detached,initial_RLOF,NaN,BH,H-rich_Core_H_burning,3.746892,9.135707,0.941797
79,9.362281e+09,step_end,initial_RLOF,END,BH,H-rich_Core_H_burning,3.746892,9.135707,0.941797