In [1]:
import pandas as pd
from pathlib import Path

# from posydon.popsyn.binarypopulation import BinaryPopulation
# from posydon.binary_evol.binarystar import BinaryStar
# from posydon.binary_evol.singlestar import SingleStar
from posydon.popsyn.synthetic_population import Population
# from posydon.popsyn.synthetic_population import PopulationRunner
# import astropy.units as u

# import os
# import shutil
# from posydon.config import PATH_TO_POSYDON

# from POSYDONHRDiagramModule import HR_Diagram
# import matplotlib.pyplot as plt
# import random as rand 

from collections import Counter

DataPath = Path().resolve().parent / 'Data'

In [2]:
cols = ['time', 'step_names', 'state', 'event', 'S1_state', 'S2_state', 'S1_mass', 'S2_mass', 'orbital_period']
finCols = [
    'orbital_period_f',
    'eccentricity_f',
    'state_f',

    'S1_state_f',
    'S2_state_f',
    
    'S2_mass_f',
    'S2_log_R_f',
    'S2_log_L_f',


    'S1_mass_f',
    'S1_log_R_f',
    'S1_log_L_f'

 ]

initCols = [
    'orbital_period_i',
    'eccentricity_i',
    'state_i',

    'S2_state_i',
    'S2_mass_i',
    'S2_log_R_i',

    'S1_state_i',
    'S1_mass_i',
    'S1_log_R_i'
 ]

In [3]:
pop = Population(str(DataPath / 'bhSolSubpop.h5'))

In [4]:
len(pop)

41191

In [5]:
# pop.calculate_formation_channels()

Formation channels already exist in the parsed population file!
Channels will be overwriten

In [6]:
Counter(pop.formation_channels['channel'])

Counter({'ZAMS_oRLO1_CC1_oRLO2_CC2_END': 14627,
         'ZAMS_oRLO1_CC1_oRLO2_CC2_maxtime_END': 8016,
         'ZAMS_CC1_oRLO2_CC2_maxtime_END': 4146,
         'ZAMS_CC1_oRLO2_CC2_END': 4133,
         'ZAMS_oRLO1_CC1_oRLO2_oCE2_oMerging2_END': 3180,
         'ZAMS_oRLO1_CC1_END': 1327,
         'ZAMS_CC1_CC2_END': 1180,
         'ZAMS_oRLO1_CC1_oRLO2_oCE2_CC2_END': 1092,
         'ZAMS_CC1_CC2_maxtime_END': 815,
         'ZAMS_CC1_oRLO2_oCE2_oMerging2_END': 413,
         'ZAMS_oRLO1_CC1_oRLO2_oCE2_CC2_maxtime_END': 338,
         'ZAMS_oCE1_CC1_oRLO2_CC2_maxtime_END': 279,
         'ZAMS_oRLO1-contact_CC1_oRLO2_oCE2_oMerging2_END': 268,
         'ZAMS_oRLO1_CC1_oRLO2_oCE2_END': 243,
         'ZAMS_oRLO1_CC1_CC2_END': 191,
         'ZAMS_oRLO1-contact_CC1_END': 158,
         'ZAMS_oRLO1_CC1_CC2_maxtime_END': 122,
         'ZAMS_oCE1_CC1_END': 99,
         'ZAMS_CC1_END': 95,
         'ZAMS_oCE1_CC1_oRLO2_oCE2_oMerging2_END': 90,
         'ZAMS_oCE1_CC1_oRLO2_CC2_END': 59,
         'ZAMS_oRLO1_CC1_maxtime_END': 51,
         'ZAMS_oRLO1-reverse_CC1_END': 44,
         'ZAMS_oRLO1-contact_CC1_oRLO2_CC2_maxtime_END': 37,
         'ZAMS_oRLO1-reverse_CC1_oRLO2_CC2_maxtime_END': 33,
         'ZAMS_oRLO1-contact_CC1_oRLO2_CC2_END': 31,
         'ZAMS_CC1_oRLO2_oCE2_CC2_maxtime_END': 31,
         'ZAMS_oRLO1-reverse_CC1_oRLO2_CC2_END': 20,
         'ZAMS_oRLO1-reverse_CC1_oRLO2_oCE2_oMerging2_END': 20,
         'ZAMS_CC1_maxtime_END': 15,
         'ZAMS_oCE1_CC1_oRLO2_CC2_FAILED': 14,
         'ZAMS_oRLO1-contact_CC1_CC2_maxtime_END': 12,
         'ZAMS_oCE1_CC1_maxtime_END': 12,
         'ZAMS_oRLO1-reverse_CC1_CC2_maxtime_END': 10,
         'ZAMS_oRLO1_CC1_oRLO2_oCE2_oCE2_oMerging2_END': 9,
         'ZAMS_CC1_oRLO2_oCE2_CC2_END': 7,
         'ZAMS_oCE1_CC1_CC2_maxtime_END': 5,
         'ZAMS_oCE1_CC1_oRLO2_maxtime_END': 5,
         'ZAMS_oRLO1_CC1_oRLO2_maxtime_END': 4,
         'ZAMS_oRLO1_CC1_FAILED_FAILED': 4,
         'ZAMS_CC1_FAILED_FAILED': 4,
         'ZAMS_oRLO1_CC1_oRLO2_oCE2_CC2_FAILED_FAILED': 3,
         'ZAMS_oRLO1-reverse_CC1_CC2_END': 2,
         'ZAMS_oRLO1_CC1_oRLO2_CC2_FAILED': 1,
         'ZAMS_CC1_oRLO2_END': 1,
         'ZAMS_oRLO1-reverse_CC1_oRLO2_oCE2_END': 1})

In [7]:
solBH_oneline_df = pop.oneline.select()
solBH_history_df = pop.history.select()

In [8]:
solBH_oneline_df

,state_i,event_i,time_i,separation_i,orbital_period_i,eccentricity_i,rl_relative_overflow_1_i,rl_relative_overflow_2_i,lg_mtransfer_rate_i,step_names_i,...,interp_class_CO_HMS_RLO,interp_class_CO_HeMS,interp_class_CO_HeMS_RLO,mt_history_HMS_HMS,mt_history_CO_HMS_RLO,mt_history_CO_HeMS,mt_history_CO_HeMS_RLO,FAILED,WARNING,metallicity
binary_index,,,,,,,,,,,,,,,,,,,,,
0,detached,ZAMS,1.354058e+10,314.927115,86.368549,0.0,NaN,NaN,NaN,initial_cond,...,stable_MT,NaN,NaN,Last stable RLOF during postMS,Last stable RLOF during postMS,NaN,NaN,0,0,1.0
1,detached,ZAMS,9.269310e+08,42.893063,4.949364,0.0,NaN,NaN,NaN,initial_cond,...,NaN,NaN,NaN,Stable contact phase,NaN,NaN,NaN,0,1,1.0
2,detached,ZAMS,7.282359e+08,83.936347,7.613953,0.0,NaN,NaN,NaN,initial_cond,...,stable_MT,NaN,NaN,no RLOF,Last stable RLOF during postMS,NaN,NaN,0,0,1.0
3,detached,ZAMS,4.896616e+08,346.312644,129.999715,0.0,NaN,NaN,NaN,initial_cond,...,stable_MT,NaN,NaN,Unstable RLOF during postMS,Last stable RLOF during stripped He star,NaN,NaN,0,1,1.0
4,detached,ZAMS,1.000807e+10,77.296905,6.337424,0.0,NaN,NaN,NaN,initial_cond,...,stable_MT,NaN,NaN,no RLOF,Last stable RLOF during postMS,NaN,NaN,0,0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41242,detached,ZAMS,8.312676e+09,79.470260,10.689626,0.0,NaN,NaN,NaN,initial_cond,...,stable_MT,NaN,NaN,Last stable RLOF during postMS,Last stable RLOF during postMS,NaN,NaN,0,0,1.0
41243,detached,ZAMS,1.067994e+10,792.218696,331.835337,0.0,NaN,NaN,NaN,initial_cond,...,stable_MT,NaN,NaN,no RLOF,Last stable RLOF during postMS,NaN,NaN,0,0,1.0
41244,detached,ZAMS,9.054567e+09,285.509574,96.941221,0.0,NaN,NaN,NaN,initial_cond,...,stable_MT,NaN,NaN,Last stable RLOF during postMS,Last stable RLOF during postMS,NaN,NaN,0,0,1.0
41245,detached,ZAMS,9.352825e+09,372.819841,154.288032,0.0,NaN,NaN,NaN,initial_cond,...,NaN,NaN,NaN,Unstable RLOF during postMS,NaN,NaN,NaN,0,1,1.0
41246,detached,ZAMS,5.687928e+09,286.403130,49.544310,0.0,NaN,NaN,NaN,initial_cond,...,stable_MT,NaN,NaN,no RLOF,Last stable RLOF during postMS,NaN,NaN,0,0,1.0

In [ ]:
sol_bhInitMask = (
    ((solBH_history_df['S1_state'] == 'BH') & (solBH_history_df['S2_state'] == 'H-rich_Core_H_burning')) |
    ((solBH_history_df['S2_state'] == 'BH') & (solBH_history_df['S1_state'] == 'H-rich_Core_H_burning'))
) & (solBH_history_df['event'] != 'END')

sol_bhMaskNext = sol_bhInitMask.groupby(level=0).shift(1, fill_value=False)

sol_bhMask = sol_bhInitMask | sol_bhMaskNext

specStatedf = solBH_history_df[sol_bhMask] ### makes a df with the row with the sol-bh and the row after. used for finding the lifespan of the systems 

sol_bhMaskFirst = pd.Series(False, index = sol_bhMask.index)
sol_bhMaskFirst = ~sol_bhMaskFirst.index.duplicated(keep='first')

firstAndsol_bh = sol_bhInitMask | sol_bhMaskFirst
### makes a mask with the init cond and the row with the bh-sol, not super useful when compared to just using bh-ms row df + oneline 

def isMW(group): ### this is wayyyyy too narrow of a process... it does work though!
    return (group['time'].iloc[0] < 10e9) & (group['time'].iloc[1] > 10e9)
TenGyr = solBH_history_df[sol_bhMask].groupby(level=0).apply(isMW)

def findStatDur(group):
        return (group['time'].iloc[1] - group['time'].iloc[0])

In [31]:
percise10GyrThresh = solBH_history_df[TenGyr]

/tmp/ipykernel_1348615/1690891484.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.

In [ ]:
percise10GyrThresh[cols]

,time,step_names,state,event,S1_state,S2_state,S1_mass,S2_mass,orbital_period
binary_index,,,,,,,,,
4706,9.963300e+09,initial_cond,detached,ZAMS,H-rich_Core_H_burning,H-rich_Core_H_burning,23.557768,6.941473,14.061326
4706,9.972059e+09,step_HMS_HMS,detached,CC1,stripped_He_Core_C_depleted,H-rich_Core_H_burning,7.102118,7.537212,1.960283
4706,9.972059e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,3.091624,7.537212,3.644188
4706,1.000254e+10,step_detached,RLO2,oRLO2,BH,H-rich_Core_H_burning,3.091624,7.559632,1.795340
4706,1.006353e+10,step_CO_HMS_RLO,detached,CC2,BH,stripped_He_Core_He_depleted,3.822794,0.757246,12.984662
...,...,...,...,...,...,...,...,...,...
40212,9.989924e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,3.709383,10.048431,16.344035
40212,1.000851e+10,step_detached,RLO2,oRLO2,BH,H-rich_Shell_H_burning,3.709383,9.683863,13.080100
40212,1.001043e+10,step_CO_HMS_RLO,detached,CC2,BH,stripped_He_Core_C_depleted,3.716679,2.778028,8.524264
40212,1.001043e+10,step_SN,disrupted,NaN,BH,NS,3.716679,1.277584,NaN
40212,1.001043e+10,step_end,disrupted,END,BH,NS,3.716679,1.277584,NaN

In [10]:
sol_bh_lifespan_list = specStatedf.groupby(level=0).apply(findStatDur)
sol_bh_FormationTime_List = solBH_history_df[firstAndsol_bh].groupby(level=0).apply(findStatDur)

In [11]:
sol_bh_lifespan_list.describe()

count    4.119100e+04
mean     7.961639e+06
std      2.094689e+07
min      0.000000e+00
25%      1.145769e+06
50%      3.525567e+06
75%      9.046779e+06
max      1.373802e+09
dtype: float64

In [12]:
sol_bh_FormationTime_List.describe()

count    4.119100e+04
mean     6.106691e+06
std      3.651581e+07
min      3.200919e+06
25%      4.176094e+06
50%      5.230424e+06
75%      6.702036e+06
max      5.568467e+09
dtype: float64

In [13]:
# tolerance = 1e9

sol_bhMaskMWdur = ((
    ((solBH_history_df['S1_state'] == 'BH') & (solBH_history_df['S2_state'] == 'H-rich_Core_H_burning'))
    )   & (solBH_history_df['event'] != 'END')
        # & (solBH_history_df['time'] > 10e9 - tolerance)
        & (solBH_history_df['time'] < 10e9)
        & (solBH_history_df['state'] == 'detached')
)

In [14]:
len(solBH_history_df[sol_bhMaskMWdur])

29759

In [15]:
solBH_history_df[sol_bhMaskMWdur][cols]

,time,step_names,state,event,S1_state,S2_state,S1_mass,S2_mass,orbital_period
binary_index,,,,,,,,,
1,9.365578e+08,step_SN,detached,NaN,BH,H-rich_Core_H_burning,2.862360,27.696843,13.464326
2,7.320985e+08,step_SN,detached,NaN,BH,H-rich_Core_H_burning,14.104784,42.583776,42.991418
3,4.982609e+08,step_SN,detached,NaN,BH,H-rich_Core_H_burning,4.339844,11.088933,10.559919
5,9.257842e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,16.217696,25.023889,2185.162950
7,5.187019e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,13.837255,30.757624,1073.146224
...,...,...,...,...,...,...,...,...,...
41241,6.492712e+08,step_SN,detached,NaN,BH,H-rich_Core_H_burning,12.734073,46.109216,263.124746
41242,8.317989e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,11.144016,17.054852,10.937788
41244,9.064239e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,3.570469,12.382211,18964.253312
41245,9.362281e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,3.746892,9.131854,0.941797
41246,5.691558e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,13.275789,32.924976,3998.959992

In [16]:
lowPorbSolBH = solBH_history_df[sol_bhMaskMWdur][solBH_history_df[sol_bhMaskMWdur]['orbital_period'] < 3]

In [17]:
lowPorbSolBH[cols]

,time,step_names,state,event,S1_state,S2_state,S1_mass,S2_mass,orbital_period
binary_index,,,,,,,,,
65,4.388148e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,3.510452,7.542214,2.552592
204,4.717553e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,3.864177,7.439176,2.078860
261,9.005453e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,2.720699,7.515792,2.597624
281,8.861886e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,2.548404,7.243093,2.914340
336,3.671609e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,3.481917,6.927287,2.674174
...,...,...,...,...,...,...,...,...,...
40849,2.593308e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,2.521511,5.991479,1.456001
40965,4.703897e+07,step_SN,detached,NaN,BH,H-rich_Core_H_burning,4.372229,12.649951,2.995665
41103,2.936772e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,2.885103,7.898216,1.440654
41150,6.852416e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,2.973341,8.338666,1.801697
41245,9.362281e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,3.746892,9.131854,0.941797

In [18]:
lowPorbSolBH.to_csv(DataPath / 'threeDayPorb_solBHPairRows.csv')

In [19]:
pop.export_selection(lowPorbSolBH.index.to_list(), str(DataPath / 'bhSol_10Gyr_LowPorb_Subpop.h5'), append=False, overwrite=True)

In [20]:
FiveDPorbSolBH = solBH_history_df[sol_bhMaskMWdur][solBH_history_df[sol_bhMaskMWdur]['orbital_period'] < 5]

In [21]:
FiveDPorbSolBH[cols]

,time,step_names,state,event,S1_state,S2_state,S1_mass,S2_mass,orbital_period
binary_index,,,,,,,,,
65,4.388148e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,3.510452,7.542214,2.552592
100,6.723392e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,6.746752,23.365053,4.711448
121,6.348326e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,4.705900,29.010861,3.227938
163,4.091260e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,4.549543,23.219983,3.035637
189,2.120485e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,2.739360,6.555099,3.598046
...,...,...,...,...,...,...,...,...,...
41093,9.813266e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,3.077906,6.586934,4.465087
41103,2.936772e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,2.885103,7.898216,1.440654
41150,6.852416e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,2.973341,8.338666,1.801697
41184,9.026899e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,3.347515,20.683932,4.818280
41245,9.362281e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,3.746892,9.131854,0.941797

In [22]:
FiveDPorbSolBH[FiveDPorbSolBH['S2_mass'] < 3]

,state,event,time,separation,orbital_period,eccentricity,rl_relative_overflow_1,rl_relative_overflow_2,lg_mtransfer_rate,step_names,...,S2_conv_env_turnover_time_l_b,S2_conv_env_turnover_time_l_t,S2_envelope_binding_energy,S2_mass_conv_reg_fortides,S2_thickness_conv_reg_fortides,S2_radius_conv_reg_fortides,S2_lambda_CE_1cent,S2_lambda_CE_10cent,S2_lambda_CE_30cent,S2_lambda_CE_pure_He_star_10cent
binary_index,,,,,,,,,,,,,,,,,,,,,
2802,detached,NaN,3.691715e+09,11.293946,1.849214,0.393189,NaN,NaN,NaN,step_SN,...,0.0,0.0,-8.827674e+48,1.590992e-09,0.003777,1.499498,1.032998,1.032998,1.032998,1.032998
8266,detached,CC2,7.081756e+09,12.713388,3.097021,0.000000,-1.0,-0.664647,-99.0,step_CO_HMS_RLO,...,0.0,0.0,-6.715622e+46,2.015284e-03,0.019752,0.010956,1.126350,1.136310,0.973289,1.257467
14233,detached,NaN,8.226639e+09,21.954497,4.797184,0.595112,NaN,NaN,NaN,step_SN,...,0.0,0.0,-1.291452e+49,1.267583e-09,0.003781,1.733125,1.087524,1.087524,1.087524,1.087524
16700,detached,NaN,6.781736e+09,16.367204,2.973241,0.304953,NaN,NaN,NaN,step_SN,...,0.0,0.0,-1.465824e+49,1.230028e-09,0.003897,1.839856,1.105396,1.105396,1.105396,1.105396
16992,detached,NaN,2.657450e+09,17.724857,3.436552,0.037662,NaN,NaN,NaN,step_SN,...,0.0,0.0,-1.315529e+49,1.263765e-09,0.003761,1.749686,1.089837,1.089837,1.089837,1.089837
20583,detached,CC2,5.462662e+09,9.700365,2.159860,0.000000,-1.0,-0.650801,-99.0,step_CO_HMS_RLO,...,0.0,0.0,-6.967921e+46,2.095514e-03,0.020497,0.011435,1.130879,1.140167,0.987501,1.284286
23416,detached,NaN,9.633998e+09,15.784547,2.778295,0.451439,NaN,NaN,NaN,step_SN,...,0.0,0.0,-1.254624e+49,1.279248e-09,0.003767,1.711091,1.083348,1.083348,1.083348,1.083348
36945,detached,NaN,8.068772e+09,4.762190,0.459428,0.917996,NaN,NaN,NaN,step_SN,...,0.0,0.0,-1.073185e+49,1.370237e-09,0.003711,1.604432,1.060673,1.060673,1.060673,1.060673
39405,detached,NaN,5.513595e+09,15.788741,2.684976,0.173288,NaN,NaN,NaN,step_SN,...,0.0,0.0,-1.479714e+49,1.219557e-09,0.003872,1.843069,1.107593,1.107593,1.107593,1.107593

In [23]:
pop.export_selection(FiveDPorbSolBH.index.to_list(), str(DataPath / 'bhSol_10Gyr_FiveDay_Subpop.h5'), append=False, overwrite=True)

In [24]:
filtPop = Population(str(DataPath / 'bhSol_10Gyr_LowPorb_Subpop.h5'))

In [25]:
len(filtPop)

454

In [26]:
filtPop.history.select()[cols]

,time,step_names,state,event,S1_state,S2_state,S1_mass,S2_mass,orbital_period
binary_index,,,,,,,,,
0,4.379912e+09,initial_cond,detached,ZAMS,H-rich_Core_H_burning,H-rich_Core_H_burning,25.281532,6.978345,14.862365
0,4.388148e+09,step_HMS_HMS,detached,CC1,stripped_He_Core_C_depleted,H-rich_Core_H_burning,7.509545,7.542214,2.124767
0,4.388148e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,3.510452,7.542214,2.552592
0,4.421309e+09,step_detached,RLO2,oRLO2,BH,H-rich_Core_H_burning,3.510452,7.610958,2.270194
0,4.448127e+09,step_CO_HMS_RLO,detached,CC2,BH,stripped_He_Core_He_depleted,4.144812,0.893005,20.743069
...,...,...,...,...,...,...,...,...,...
453,9.362273e+09,step_CE,detached,NaN,stripped_He_non_burning,H-rich_Core_H_burning,7.457188,9.061668,1.493836
453,9.362281e+09,step_detached,detached,CC1,stripped_He_Core_He_depleted,H-rich_Core_H_burning,7.396282,9.131854,1.514407
453,9.362281e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,3.746892,9.131854,0.941797
453,9.362281e+09,step_detached,initial_RLOF,NaN,BH,H-rich_Core_H_burning,3.746892,9.135707,0.941797
453,9.362281e+09,step_end,initial_RLOF,END,BH,H-rich_Core_H_burning,3.746892,9.135707,0.941797