In [1]:
import pandas as pd
from pathlib import Path

# from posydon.popsyn.binarypopulation import BinaryPopulation
# from posydon.binary_evol.binarystar import BinaryStar
# from posydon.binary_evol.singlestar import SingleStar
from posydon.popsyn.synthetic_population import Population
# from posydon.popsyn.synthetic_population import PopulationRunner
# import astropy.units as u

# import os
# import shutil
# from posydon.config import PATH_TO_POSYDON

# from POSYDONHRDiagramModule import HR_Diagram
# import matplotlib.pyplot as plt
# import random as rand 

from collections import Counter

DataPath = Path().resolve().parent / 'Data'

In [7]:
cols = ['time', 'step_names', 'state', 'event', 'S1_state', 'S2_state', 'S1_mass', 'S2_mass', 'orbital_period']
finCols = [
    'orbital_period_f',
    'eccentricity_f',
    'state_f',

    'S1_state_f',
    'S2_state_f',
    
    'S2_mass_f',
    'S2_log_R_f',
    'S2_log_L_f',


    'S1_mass_f',
    'S1_log_R_f',
    'S1_log_L_f'

 ]

initCols = [
    'orbital_period_i',
    'eccentricity_i',
    'state_i',

    'S2_state_i',
    'S2_mass_i',
    'S2_log_R_i',

    'S1_state_i',
    'S1_mass_i',
    'S1_log_R_i'
 ]

In [2]:
pop = Population('/home/bku2126/b1095/bku2126/stellarBHs/Notebooks/1e+00_Zsun_population.h5')

In [3]:
df = pop.history.select()

In [4]:
df

,state,event,time,separation,orbital_period,eccentricity,rl_relative_overflow_1,rl_relative_overflow_2,lg_mtransfer_rate,step_names,...,S2_conv_env_turnover_time_l_b,S2_conv_env_turnover_time_l_t,S2_envelope_binding_energy,S2_mass_conv_reg_fortides,S2_thickness_conv_reg_fortides,S2_radius_conv_reg_fortides,S2_lambda_CE_1cent,S2_lambda_CE_10cent,S2_lambda_CE_30cent,S2_lambda_CE_pure_He_star_10cent
binary_index,,,,,,,,,,,,,,,,,,,,,
0,detached,ZAMS,8.285364e+09,23.122776,4.028920,0.0,NaN,NaN,NaN,initial_cond,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,detached,CC1,8.359135e+09,17.783666,3.967620,0.0,-0.997256,-0.721267,-99.000000,step_HMS_HMS,...,0.000000e+00,-1.341968e+98,-2.105081e+49,7.074786e-09,0.023184,2.472419,1.098633,1.098633,0.762833,1.108842
0,detached,NaN,8.359135e+09,17.808993,3.979517,0.0,NaN,NaN,NaN,step_SN,...,0.000000e+00,-1.341968e+98,-2.105081e+49,7.074786e-09,0.023184,2.472419,1.098633,1.098633,0.762833,1.108842
0,RLO2,oRLO2,8.480731e+09,18.871556,4.387893,0.0,-1.000000,-0.050000,NaN,step_detached,...,-3.168754e+91,-1.000000e+99,-1.267503e+49,1.763189e-07,0.069304,8.907366,0.419586,0.425345,0.431061,0.433203
0,ERR,FAILED,8.480731e+09,18.871556,4.387893,0.0,-1.000000,-0.050000,NaN,,...,-3.168754e+91,-1.000000e+99,-1.267503e+49,1.763189e-07,0.069304,8.907366,0.419586,0.425345,0.431061,0.433203
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999999,detached,ZAMS,1.293519e+10,661.754383,599.008784,0.0,NaN,NaN,NaN,initial_cond,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
999999,RLO1,oCE1,1.298554e+10,505.289770,427.471399,0.0,0.215464,-0.975639,-0.986324,step_HMS_HMS,...,0.000000e+00,0.000000e+00,-1.929615e+49,4.080671e-02,0.016185,0.271448,0.626245,0.626245,0.626245,0.626245
999999,detached,NaN,1.298554e+10,19.510997,4.357483,0.0,NaN,NaN,NaN,step_CE,...,0.000000e+00,0.000000e+00,-1.929615e+49,4.080671e-02,0.016185,0.271448,0.626245,0.626245,0.626245,0.626245
999999,ERR,FAILED,1.298554e+10,19.510997,4.357483,0.0,NaN,NaN,NaN,,...,0.000000e+00,0.000000e+00,-1.929615e+49,4.080671e-02,0.016185,0.271448,0.626245,0.626245,0.626245,0.626245
999999,ERR,FAILED,1.298554e+10,19.510997,4.357483,0.0,NaN,NaN,NaN,,...,0.000000e+00,0.000000e+00,-1.929615e+49,4.080671e-02,0.016185,0.271448,0.626245,0.626245,0.626245,0.626245

In [40]:

sol_bhMaskMWdur = ((
    ((df['S1_state'] == 'BH') & (df['S2_state'] == 'H-rich_Core_H_burning'))
    )   & (df['event'] != 'END')
        # & (df['time'] > 10e9 - tolerance)
        & (df['time'] < 10e9)
        & (df['state'] == 'detached')
)

In [41]:
filtered_df = df[sol_bhMaskMWdur]

In [42]:
filtered_df[filtered_df['S2_mass'] < 3][cols]

,time,step_names,state,event,S1_state,S2_state,S1_mass,S2_mass,orbital_period
binary_index,,,,,,,,,
6172,1.581094e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,2.751273,1.916033,15950.270637
53886,8.688226e+08,step_SN,detached,NaN,BH,H-rich_Core_H_burning,11.049904,2.979379,3313.121388
68561,3.691715e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,3.747350,1.911536,1.849214
122211,1.258932e+08,step_SN,detached,NaN,BH,H-rich_Core_H_burning,5.285030,2.640095,30795.391506
198138,7.969938e+09,step_CO_HMS_RLO,detached,CC2,BH,H-rich_Core_H_burning,3.763195,0.428597,13.715771
199300,7.081756e+09,step_CO_HMS_RLO,detached,CC2,BH,H-rich_Core_H_burning,2.785568,0.091402,3.097021
297776,7.838231e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,11.682664,2.949888,366033.836496
344806,8.226639e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,3.628408,2.548425,4.797184
402228,8.448889e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,3.136513,1.793448,8.204241
403504,6.781736e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,3.842919,2.819491,2.973241
410679,2.657450e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,3.746921,2.586967,3.436552
495833,5.462662e+09,step_CO_HMS_RLO,detached,CC2,BH,H-rich_Core_H_burning,2.543167,0.084394,2.159860
521800,5.092341e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,11.596710,2.999731,10756.217217
563444,2.652308e+09,step_CO_HMS_RLO,detached,CC2,BH,H-rich_Core_H_burning,2.645931,0.199414,10.347254
563655,9.633998e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,4.352769,2.491193,2.778295
566096,3.552426e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,4.495552,2.830279,14.513940
687885,1.838100e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,12.150655,2.963669,1806.189120
709207,7.691715e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,4.163955,2.834896,23.354351
801466,9.792912e+09,step_CO_HMS_RLO,detached,CC2,BH,H-rich_Core_H_burning,3.472458,0.280163,8.962438
839107,5.565634e+09,step_CO_HMS_RLO,detached,CC2,BH,H-rich_Core_H_burning,2.614052,0.232999,11.361084
863874,5.563134e+09,step_CO_HMS_RLO,detached,CC2,BH,H-rich_Core_H_burning,3.011468,0.262993,9.397414
893211,8.068772e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,4.664751,2.208363,0.459428
954453,5.513595e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,4.495786,2.838026,2.684976
982287,2.239707e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,3.630861,1.962480,24.633727

In [39]:
df.loc[34222][cols]

,time,step_names,state,event,S1_state,S2_state,S1_mass,S2_mass,orbital_period
binary_index,,,,,,,,,
34222,7.816161e+09,initial_cond,detached,ZAMS,H-rich_Core_H_burning,H-rich_Core_H_burning,18.488846,6.041695,673.205977
34222,7.826776e+09,step_HMS_HMS,RLO1,oCE1,H-rich_Shell_H_burning,H-rich_Core_H_burning,11.651054,6.150812,252.112118
34222,7.826776e+09,step_CE,detached,NaN,stripped_He_non_burning,H-rich_Core_H_burning,6.518232,6.117600,0.887240
34222,7.826784e+09,step_detached,detached,CC1,stripped_He_Core_C_depleted,H-rich_Core_H_burning,6.493311,6.117590,0.900957
34222,7.826784e+09,step_SN,detached,NaN,NS,H-rich_Core_H_burning,2.493044,6.117590,3.532180
34222,7.853264e+09,step_detached,RLO2,oRLO2,NS,H-rich_Core_H_burning,2.493044,6.111617,1.026671
34222,7.863070e+09,step_CO_HMS_RLO,RLO2,oCE2,BH,H-rich_Core_H_burning,3.329968,0.704356,0.183356
34222,7.863070e+09,step_CE,merged,oMerging2,BH,H-rich_Core_H_burning,3.329968,0.704356,0.183356
34222,1.380000e+10,step_merged,merged,NaN,BH,massless_remnant,3.329968,0.000000,NaN
34222,1.380000e+10,step_end,merged,END,BH,massless_remnant,3.329968,0.000000,NaN