In [ ]:
import pandas as pd
from pathlib import Path

# from posydon.popsyn.binarypopulation import BinaryPopulation
# from posydon.binary_evol.binarystar import BinaryStar
# from posydon.binary_evol.singlestar import SingleStar
from posydon.popsyn.synthetic_population import Population
# from posydon.popsyn.synthetic_population import PopulationRunner
# import astropy.units as u

# import os
# import shutil
# from posydon.config import PATH_TO_POSYDON

# from POSYDONHRDiagramModule import HR_Diagram
# import matplotlib.pyplot as plt
# import random as rand 

from collections import Counter

DataPath = Path().resolve().parent / 'Data'

In [ ]:
cols = ['time', 'step_names', 'state', 'event', 'S1_state', 'S2_state', 'S1_mass', 'S2_mass', 'orbital_period']
finCols = [
    'orbital_period_f',
    'eccentricity_f',
    'state_f',

    'S1_state_f',
    'S2_state_f',
    
    'S2_mass_f',
    'S2_log_R_f',
    'S2_log_L_f',


    'S1_mass_f',
    'S1_log_R_f',
    'S1_log_L_f'

 ]

initCols = [
    'orbital_period_i',
    'eccentricity_i',
    'state_i',

    'S2_state_i',
    'S2_mass_i',
    'S2_log_R_i',

    'S1_state_i',
    'S1_mass_i',
    'S1_log_R_i'
 ]

In [ ]:
pop = Population('/home/bku2126/b1095/bku2126/stellarBHs/Data/1e+00_Zsun_population.h5')

In [ ]:
pop.ini_params

{'metallicity': 1.0,
 'number_of_binaries': 1000000,
 'binary_fraction_scheme': 'const',
 'binary_fraction_const': 1.0,
 'star_formation': 'constant',
 'max_simulation_time': 13800000000.0,
 'primary_mass_scheme': 'Kroupa2001',
 'primary_mass_min': 4,
 'primary_mass_max': 150.0,
 'secondary_mass_scheme': 'Moe+17-PsandQs',
 'secondary_mass_min': 0.1,
 'secondary_mass_max': 150.0,
 'orbital_scheme': 'period',
 'orbital_period_scheme': 'Moe+17-PsandQs',
 'orbital_period_min': 0.75,
 'orbital_period_max': 6000.0,
 'orbital_separation_scheme': 'log_uniform',
 'orbital_separation_min': 5.0,
 'orbital_separation_max': 100000.0,
 'eccentricity_scheme': 'zero'}

In [ ]:
len(pop)

1000000

In [ ]:
df = pop.history.select()
dfOnline = pop.oneline.select()

In [ ]:
dfOnline[initCols].describe()

,orbital_period_i,eccentricity_i,S2_mass_i,S2_log_R_i,S1_mass_i,S1_log_R_i
count,633340.000000,633340.0,1000000.000000,633340.0,1000000.000000,1000000.0
mean,660.069380,0.0,4.216327,0.0,11.618591,0.0
std,1221.202401,0.0,8.697919,0.0,14.702374,0.0
min,0.750001,0.0,0.000000,0.0,4.000001,0.0
25%,7.300385,0.0,0.000000,0.0,4.980537,0.0
50%,70.292423,0.0,1.690187,0.0,6.778029,0.0
75%,653.408100,0.0,4.557395,0.0,11.405791,0.0
max,5999.956810,0.0,148.877088,0.0,149.975532,0.0

In [ ]:
dfOneline['eccentricity_i'].value_counts()

:

In [ ]:
df

,state,event,time,separation,orbital_period,eccentricity,rl_relative_overflow_1,rl_relative_overflow_2,lg_mtransfer_rate,step_names,...,S2_conv_env_turnover_time_l_b,S2_conv_env_turnover_time_l_t,S2_envelope_binding_energy,S2_mass_conv_reg_fortides,S2_thickness_conv_reg_fortides,S2_radius_conv_reg_fortides,S2_lambda_CE_1cent,S2_lambda_CE_10cent,S2_lambda_CE_30cent,S2_lambda_CE_pure_He_star_10cent
binary_index,,,,,,,,,,,,,,,,,,,,,
0,detached,ZAMS,8.285364e+09,23.122776,4.028920,0.0,NaN,NaN,NaN,initial_cond,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,detached,CC1,8.359135e+09,17.783666,3.967620,0.0,-0.997256,-0.721267,-99.000000,step_HMS_HMS,...,0.000000e+00,-1.341968e+98,-2.105081e+49,7.074786e-09,0.023184,2.472419,1.098633,1.098633,0.762833,1.108842
0,detached,NaN,8.359135e+09,17.808993,3.979517,0.0,NaN,NaN,NaN,step_SN,...,0.000000e+00,-1.341968e+98,-2.105081e+49,7.074786e-09,0.023184,2.472419,1.098633,1.098633,0.762833,1.108842
0,RLO2,oRLO2,8.480731e+09,18.871556,4.387893,0.0,-1.000000,-0.050000,NaN,step_detached,...,-3.168754e+91,-1.000000e+99,-1.267503e+49,1.763189e-07,0.069304,8.907366,0.419586,0.425345,0.431061,0.433203
0,ERR,FAILED,8.480731e+09,18.871556,4.387893,0.0,-1.000000,-0.050000,NaN,,...,-3.168754e+91,-1.000000e+99,-1.267503e+49,1.763189e-07,0.069304,8.907366,0.419586,0.425345,0.431061,0.433203
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999999,detached,ZAMS,1.293519e+10,661.754383,599.008784,0.0,NaN,NaN,NaN,initial_cond,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
999999,RLO1,oCE1,1.298554e+10,505.289770,427.471399,0.0,0.215464,-0.975639,-0.986324,step_HMS_HMS,...,0.000000e+00,0.000000e+00,-1.929615e+49,4.080671e-02,0.016185,0.271448,0.626245,0.626245,0.626245,0.626245
999999,detached,NaN,1.298554e+10,19.510997,4.357483,0.0,NaN,NaN,NaN,step_CE,...,0.000000e+00,0.000000e+00,-1.929615e+49,4.080671e-02,0.016185,0.271448,0.626245,0.626245,0.626245,0.626245
999999,ERR,FAILED,1.298554e+10,19.510997,4.357483,0.0,NaN,NaN,NaN,,...,0.000000e+00,0.000000e+00,-1.929615e+49,4.080671e-02,0.016185,0.271448,0.626245,0.626245,0.626245,0.626245
999999,ERR,FAILED,1.298554e+10,19.510997,4.357483,0.0,NaN,NaN,NaN,,...,0.000000e+00,0.000000e+00,-1.929615e+49,4.080671e-02,0.016185,0.271448,0.626245,0.626245,0.626245,0.626245

In [ ]:
sol_bhMaskMWdur = ((
    ((df['S1_state'] == 'BH') & (df['S2_state'] == 'H-rich_Core_H_burning'))
    )   & (df['event'] != 'END')
        # & (df['time'] > 10e9 - tolerance)
        # & (df['time'] < 10e9)
        & (df['state'] == 'detached')
)

In [ ]:
filtered_df = df[sol_bhMaskMWdur]

In [ ]:
filtered_df[filtered_df['S2_mass'] < 2.3]

,state,event,time,separation,orbital_period,eccentricity,rl_relative_overflow_1,rl_relative_overflow_2,lg_mtransfer_rate,step_names,...,S2_conv_env_turnover_time_l_b,S2_conv_env_turnover_time_l_t,S2_envelope_binding_energy,S2_mass_conv_reg_fortides,S2_thickness_conv_reg_fortides,S2_radius_conv_reg_fortides,S2_lambda_CE_1cent,S2_lambda_CE_10cent,S2_lambda_CE_30cent,S2_lambda_CE_pure_He_star_10cent
binary_index,,,,,,,,,,,,,,,,,,,,,
6172,detached,NaN,1.581094e+09,4454.628003,15950.270637,0.342464,NaN,NaN,NaN,step_SN,...,0.000000,0.000000e+00,-8.871533e+48,1.570383e-09,0.003752,1.495985,1.035170,1.035170,1.035170,1.035170
68561,detached,NaN,3.691715e+09,11.293946,1.849214,0.393189,NaN,NaN,NaN,step_SN,...,0.000000,0.000000e+00,-8.827674e+48,1.590992e-09,0.003777,1.499498,1.032998,1.032998,1.032998,1.032998
198138,detached,CC2,7.969938e+09,38.868713,13.715771,0.000000,-1.0,-0.980027,-99.0,step_CO_HMS_RLO,...,0.000000,0.000000e+00,-4.384726e+46,1.161296e-04,0.001144,0.006996,1.264195,1.267722,1.094838,1.327608
199300,detached,CC2,7.081756e+09,12.713388,3.097021,0.000000,-1.0,-0.664647,-99.0,step_CO_HMS_RLO,...,0.000000,0.000000e+00,-6.715622e+46,2.015284e-03,0.019752,0.010956,1.126350,1.136310,0.973289,1.257467
402228,detached,NaN,8.448889e+09,29.123980,8.204241,0.578822,NaN,NaN,NaN,step_SN,...,0.013671,-1.000000e+99,-8.059624e+48,1.778157e-09,0.003942,1.463550,1.020137,1.020137,1.020137,1.020137
495833,detached,CC2,5.462662e+09,9.700365,2.159860,0.000000,-1.0,-0.650801,-99.0,step_CO_HMS_RLO,...,0.000000,0.000000e+00,-6.967921e+46,2.095514e-03,0.020497,0.011435,1.130879,1.140167,0.987501,1.284286
563444,detached,CC2,2.652308e+09,28.308390,10.347254,0.000000,-1.0,-0.834492,-99.0,step_CO_HMS_RLO,...,0.000000,0.000000e+00,-6.864888e+46,1.010123e-03,0.009223,0.006534,1.011894,1.023319,1.111730,1.069018
801466,detached,CC2,9.792912e+09,28.208660,8.962438,0.000000,-1.0,-0.922647,-99.0,step_CO_HMS_RLO,...,0.000000,0.000000e+00,-8.391861e+46,4.701203e-04,0.004381,0.010114,1.128921,1.139247,1.318090,1.454377
839107,detached,CC2,5.565634e+09,30.134573,11.361084,0.000000,-1.0,-0.859921,-99.0,step_CO_HMS_RLO,...,0.000000,0.000000e+00,-5.931346e+46,8.535082e-04,0.007793,0.005521,1.000219,1.011805,1.090096,1.008136
863874,detached,CC2,5.563134e+09,27.820970,9.397414,0.000000,-1.0,-0.936285,-99.0,step_CO_HMS_RLO,...,0.000000,0.000000e+00,-1.079841e+47,3.835294e-04,0.003586,0.009239,0.988552,1.003038,1.303043,1.447136
893211,detached,NaN,8.068772e+09,4.762190,0.459428,0.917996,NaN,NaN,NaN,step_SN,...,0.000000,0.000000e+00,-1.073185e+49,1.370237e-09,0.003711,1.604432,1.060673,1.060673,1.060673,1.060673
982287,detached,NaN,2.239707e+09,63.219998,24.633727,0.692888,NaN,NaN,NaN,step_SN,...,0.000000,0.000000e+00,-9.152301e+48,1.538458e-09,0.003805,1.517656,1.037700,1.037700,1.037700,1.037700

In [ ]:
df[
    (df['S1_state'] == 'BH') & (df['S2_state'] == 'H-rich_Core_H_burning')
    &  (df['state'] == 'detached')
    &  (df['S2_mass'] < 2.5) & (df['orbital_period'] < 3.5)
    ][cols]

,time,step_names,state,event,S1_state,S2_state,S1_mass,S2_mass,orbital_period
binary_index,,,,,,,,,
68561,3.691715e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,3.747350,1.911536,1.849214
199300,7.081756e+09,step_CO_HMS_RLO,detached,CC2,BH,H-rich_Core_H_burning,2.785568,0.091402,3.097021
357232,1.380000e+10,NaN,detached,maxtime,BH,H-rich_Core_H_burning,2.690295,0.021281,0.046032
357232,1.380000e+10,step_end,detached,END,BH,H-rich_Core_H_burning,2.690295,0.021281,0.046032
495833,5.462662e+09,step_CO_HMS_RLO,detached,CC2,BH,H-rich_Core_H_burning,2.543167,0.084394,2.159860
563655,9.633998e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,4.352769,2.491193,2.778295
893211,8.068772e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,4.664751,2.208363,0.459428

In [ ]:
sol_bhInitMask = (
    ((df['S1_state'] == 'BH') & (df['S2_state'] == 'H-rich_Core_H_burning'))
    # ((df['S2_state'] == 'BH') & (df['S1_state'] == 'H-rich_Core_H_burning'))
) &  (df['state'] == 'detached')


sol_bhMaskNext = sol_bhInitMask.groupby(level=0).shift(1, fill_value=False)

sol_bhMask = sol_bhInitMask | sol_bhMaskNext

specStatedf = df[sol_bhMask] ### makes a df with the row with the sol-bh and the row after. used for finding the lifespan of the systems 

sol_bhMaskFirst = pd.Series(False, index = sol_bhMask.index)
sol_bhMaskFirst = ~sol_bhMaskFirst.index.duplicated(keep='first')

firstAndsol_bh = sol_bhInitMask | sol_bhMaskFirst
### makes a mask with the init cond and the row with the bh-sol, not super useful when compared to just using bh-ms row df + oneline 

def isMW(group): ### this is wayyyyy too narrow of a process... it does work though!
    return (group['time'].iloc[0] < 10e9) & (group['time'].iloc[1] > 10e9)
TenGyr = df[sol_bhMask].groupby(level=0).apply(isMW)

def isMW2(group): ### this is wayyyyy too narrow of a process... it does work though!
    return (group['time'].iloc[0] < 10e9) & (group['time'].iloc[-1] > 10e9)
FullDFTenGyrMask = df.groupby(level=0).apply(isMW2)
def findStatDur(group):
        return (group['time'].iloc[1] - group['time'].iloc[0])

In [ ]:
df[FullDFTenGyrMask].index.nunique()

/tmp/ipykernel_3237259/2818962244.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.

67102

In [ ]:
df[FullDFTenGyrMask]

/tmp/ipykernel_3237259/2774504336.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.

,state,event,time,separation,orbital_period,eccentricity,rl_relative_overflow_1,rl_relative_overflow_2,lg_mtransfer_rate,step_names,...,S2_conv_env_turnover_time_l_b,S2_conv_env_turnover_time_l_t,S2_envelope_binding_energy,S2_mass_conv_reg_fortides,S2_thickness_conv_reg_fortides,S2_radius_conv_reg_fortides,S2_lambda_CE_1cent,S2_lambda_CE_10cent,S2_lambda_CE_30cent,S2_lambda_CE_pure_He_star_10cent
binary_index,,,,,,,,,,,,,,,,,,,,,
10,detached,ZAMS,1.264866e+09,1611.272557,2853.758189,0.0,NaN,NaN,NaN,initial_cond,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,detached,CC1,1.379082e+09,2966.758024,9980.704585,0.0,-0.921184,-0.998619,-90.532387,step_HMS_HMS,...,0.0,-6.624153e+98,-8.858761e+48,0.010759,0.013329,1.389870,1.009376e+00,1.009376e+00,1.009376e+00,1.010305
10,detached,NaN,1.379082e+09,3736.636100,15835.171890,0.0,NaN,NaN,NaN,step_SN,...,0.0,-6.624153e+98,-8.858761e+48,0.010759,0.013329,1.389870,1.009376e+00,1.009376e+00,1.009376e+00,1.010305
10,detached,CC2,2.674916e+09,8536.563219,74274.061027,0.0,-1.000000,-0.999994,NaN,step_detached,...,0.0,0.000000e+00,-1.038202e+46,0.000000,0.000000,0.000000,6.194448e+98,6.194448e+98,6.194448e+98,1.904796
10,detached,NaN,2.674916e+09,8656.689104,76379.126885,0.0,NaN,NaN,NaN,step_SN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999985,detached,NaN,4.227278e+09,5221.395761,30377.875136,0.0,NaN,NaN,NaN,step_SN,...,0.0,0.000000e+00,-3.927159e+48,0.005838,0.107979,0.802218,1.196278e+00,1.199644e+00,1.196278e+00,1.196278
999985,detached,CC2,1.034905e+10,7465.626572,62152.163007,0.0,-1.000000,-0.999993,NaN,step_detached,...,0.0,0.000000e+00,-3.376127e+46,0.000000,0.000000,0.000000,8.612397e-01,8.674992e-01,8.728985e-01,1.753510
999985,detached,NaN,1.034905e+10,7644.537644,65166.765977,0.0,NaN,NaN,NaN,step_SN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
999985,detached,maxtime,1.380000e+10,7644.537644,65166.765977,0.0,-1.000000,-1.000000,NaN,step_dco,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
999985,detached,END,1.380000e+10,7644.537644,65166.765977,0.0,-1.000000,-1.000000,NaN,step_end,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
solBhs = df[sol_bhMask]
SolBH10Gyr = solBhs[TenGyr]

detachedState = SolBH10Gyr[SolBH10Gyr['step_names'] == 'step_SN']

/tmp/ipykernel_3237259/2669472495.py:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.

In [ ]:
detachedState[cols]

,time,step_names,state,event,S1_state,S2_state,S1_mass,S2_mass,orbital_period
binary_index,,,,,,,,,
115941,9.972059e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,3.091624,7.537212,3.644188
162444,9.998314e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,2.908801,12.660248,672.279756
166117,9.993887e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,16.965615,18.407261,31.123508
282843,9.991966e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,19.448029,9.210774,1405.281610
303421,9.995698e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,12.198113,8.300179,181430.861936
326549,9.989270e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,23.592582,14.951399,9959.056674
341400,9.997352e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,2.943107,14.358771,301.044267
407686,9.607671e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,8.219198,3.062020,12870.165715
454861,9.823368e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,12.323838,4.040776,20338.118796
503621,9.839274e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,12.800980,3.553614,38922.735348
517348,9.993529e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,3.071852,7.913187,12.967199
563655,9.633998e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,4.352769,2.491193,2.778295
613202,9.983104e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,20.162413,7.895929,1794.640372
643508,9.993437e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,12.582534,11.190474,2681.228806
706977,9.984346e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,14.158589,8.609096,47.498163
728195,9.959058e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,12.096233,7.495170,36.465526
746845,9.984231e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,9.165623,8.413085,54.914868
819526,9.988061e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,13.924864,12.624693,37872.557699
870495,9.995758e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,12.685769,16.822873,1388.161257
886786,9.995723e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,12.999065,11.843004,870.344023
895592,9.868859e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,3.493515,3.406378,23818.370124
912534,9.999157e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,3.426813,10.814838,20.198982
946917,9.997892e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,13.360833,10.005710,2988.515309
966537,9.995129e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,12.300525,10.774756,478.618033
972055,9.982113e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,6.896362,9.848378,35.706447
973736,9.989924e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,3.709383,10.048431,16.344035

In [ ]:
detachedState[detachedState['S2_mass'] < 2.3][cols]

Empty DataFrame
Columns: [time, step_names, state, event, S1_state, S2_state, S1_mass, S2_mass, orbital_period]
Index: []

,state,event,time,separation,orbital_period,eccentricity,rl_relative_overflow_1,rl_relative_overflow_2,lg_mtransfer_rate,step_names,...,S2_conv_env_turnover_time_l_b,S2_conv_env_turnover_time_l_t,S2_envelope_binding_energy,S2_mass_conv_reg_fortides,S2_thickness_conv_reg_fortides,S2_radius_conv_reg_fortides,S2_lambda_CE_1cent,S2_lambda_CE_10cent,S2_lambda_CE_30cent,S2_lambda_CE_pure_He_star_10cent
binary_index,,,,,,,,,,,,,,,,,,,,,
115941,detached,NaN,9.972059e+09,21.903138,3.644188,0.429387,NaN,NaN,NaN,step_SN,...,0.000000e+00,0.000000e+00,-4.932749e+49,2.880379e-01,0.073060,0.792897,1.599897,1.599897,1.599897,1.600981
162444,detached,NaN,9.998314e+09,806.116890,672.279756,0.732237,NaN,NaN,NaN,step_SN,...,0.000000e+00,0.000000e+00,-8.499472e+49,3.686833e-06,0.191501,6.509574,1.003245,1.003245,1.003245,1.003718
166117,detached,NaN,9.993887e+09,136.634316,31.123508,0.091324,NaN,NaN,NaN,step_SN,...,0.000000e+00,0.000000e+00,-1.434857e+50,3.061537e-06,0.221940,6.930792,1.223370,1.223370,1.223370,1.223430
282843,detached,NaN,9.991966e+09,1615.122841,1405.281610,0.402936,NaN,NaN,NaN,step_SN,...,0.000000e+00,0.000000e+00,-6.385745e+49,3.510914e-08,0.012676,3.800756,1.334806,1.335093,1.334806,1.334806
303421,detached,NaN,9.995698e+09,36896.964134,181430.861936,0.910522,NaN,NaN,NaN,step_SN,...,0.000000e+00,0.000000e+00,-5.476706e+49,1.484804e-08,0.007082,3.675662,1.294064,1.294064,1.294064,1.294124
303421,detached,CC2,1.002979e+10,37901.950019,192726.805876,0.909613,-1.0,-0.415234,NaN,step_detached,...,1.387422e-02,4.389213e+05,-1.586105e+47,4.539062e+00,669.536752,338.529463,0.659974,0.886472,1.137406,0.002136
326549,detached,NaN,9.989270e+09,6577.713572,9959.056674,0.390445,NaN,NaN,NaN,step_SN,...,0.000000e+00,0.000000e+00,-1.103731e+50,5.852125e-07,0.051483,5.371603,1.405984,1.406020,1.405984,1.405984
326549,detached,CC2,1.000003e+10,6494.351437,10564.158867,0.145290,-1.0,-0.453914,NaN,step_detached,...,1.494675e-02,4.690546e+05,-2.909537e+48,3.074174e-02,0.000586,0.009104,0.039445,0.054136,0.111982,0.000897
341400,detached,NaN,9.997352e+09,488.722071,301.044267,0.856081,NaN,NaN,NaN,step_SN,...,0.000000e+00,0.000000e+00,-9.555025e+49,5.684754e-06,0.292200,7.643016,0.971713,0.971713,0.971713,0.971894
407686,detached,NaN,9.607671e+09,5181.458798,12870.165715,0.637711,NaN,NaN,NaN,step_SN,...,0.000000e+00,0.000000e+00,-1.677649e+49,1.217564e-09,0.006320,1.912361,1.126547,1.127050,1.126547,1.126547
407686,detached,CC2,1.000925e+10,5686.656932,16656.850218,0.576985,-1.0,-0.999964,NaN,step_detached,...,0.000000e+00,0.000000e+00,-1.621174e+46,0.000000e+00,0.000000,0.000000,0.880753,0.886148,0.890979,1.764241
454861,detached,NaN,9.823368e+09,7957.678838,20338.118796,0.525775,NaN,NaN,NaN,step_SN,...,-4.600354e+98,-4.600354e+98,-2.358472e+49,1.609762e-05,0.032373,1.246060,1.179583,1.180056,1.179583,1.179583
454861,detached,CC2,1.000451e+10,9835.821477,31139.548231,0.523231,-1.0,-0.999984,NaN,step_detached,...,0.000000e+00,0.000000e+00,-7.199467e+45,0.000000e+00,0.000000,0.000000,0.906278,0.911584,0.916221,1.859212
503621,detached,NaN,9.839274e+09,12263.829991,38922.735348,0.309792,NaN,NaN,NaN,step_SN,...,0.000000e+00,0.000000e+00,-1.975754e+49,1.101355e-09,0.003914,2.074039,1.157328,1.157328,1.157328,1.157328
503621,detached,CC2,1.009915e+10,15851.346472,62774.954350,0.309784,-1.0,-0.999993,NaN,step_detached,...,0.000000e+00,0.000000e+00,-5.952493e+45,0.000000e+00,0.000000,0.000000,0.921752,0.929281,0.938578,1.913672
517348,detached,NaN,9.993529e+09,51.614922,12.967199,0.438436,NaN,NaN,NaN,step_SN,...,0.000000e+00,0.000000e+00,-5.252549e+49,2.246626e-07,0.019197,3.674564,1.208760,1.208760,1.208760,1.209670
563655,detached,NaN,9.633998e+09,15.784547,2.778295,0.451439,NaN,NaN,NaN,step_SN,...,0.000000e+00,0.000000e+00,-1.254624e+49,1.279248e-09,0.003767,1.711091,1.083348,1.083348,1.083348,1.083348
613202,detached,NaN,9.983104e+09,1887.772214,1794.640372,0.168655,NaN,NaN,NaN,step_SN,...,0.000000e+00,0.000000e+00,-5.301663e+49,1.186412e-09,0.016397,3.427339,1.310270,1.310561,1.310270,1.310270
643508,detached,NaN,9.993437e+09,2334.503860,2681.228806,0.499310,NaN,NaN,NaN,step_SN,...,0.000000e+00,0.000000e+00,-7.937217e+49,7.559678e-07,0.049306,4.762811,1.221901,1.221901,1.221901,1.221959
706977,detached,NaN,9.984346e+09,156.375292,47.498163,0.220425,NaN,NaN,NaN,step_SN,...,0.000000e+00,0.000000e+00,-6.169484e+49,8.866384e-01,0.170278,1.882152,1.238185,1.238185,1.238185,1.241697
728195,detached,NaN,9.959058e+09,124.706035,36.465526,0.404915,NaN,NaN,NaN,step_SN,...,0.000000e+00,0.000000e+00,-5.128905e+49,2.772529e-07,0.029180,3.686314,1.118432,1.118432,1.118432,1.118540
746845,detached,NaN,9.984231e+09,158.027588,54.914868,0.755551,NaN,NaN,NaN,step_SN,...,0.000000e+00,0.000000e+00,-5.786576e+49,2.030718e-07,0.026550,3.646145,1.243353,1.243353,1.243353,1.247517
819526,detached,NaN,9.988061e+09,14152.923220,37872.557699,0.978861,NaN,NaN,NaN,step_SN,...,0.000000e+00,0.000000e+00,-8.929207e+49,6.400324e-07,0.047782,5.037114,1.314188,1.314188,1.314188,1.315322
870495,detached,NaN,9.995758e+09,1617.659044,1388.161257,0.673457,NaN,NaN,NaN,step_SN,...,0.000000e+00,0.000000e+00,-1.234675e+50,2.871301e-06,0.193498,7.090147,1.150603,1.150603,1.150603,1.151622
886786,detached,NaN,9.995723e+09,1118.923828,870.344023,0.073769,NaN,NaN,NaN,step_SN,...,0.000000e+00,0.000000e+00,-8.473611e+49,9.243498e-07,0.059921,4.983134,1.215390,1.215390,1.215390,1.215578
895592,detached,NaN,9.868859e+09,6629.784890,23818.370124,0.531882,NaN,NaN,NaN,step_SN,...,0.000000e+00,0.000000e+00,-1.892249e+49,1.188190e-09,0.004585,2.058161,1.141737,1.142082,1.141737,1.141737
895592,detached,CC2,1.015647e+10,12138.588121,75290.206467,0.531349,-1.0,-0.999990,NaN,step_detached,...,0.000000e+00,0.000000e+00,-5.870771e+45,0.000000e+00,0.000000,0.000000,0.929854,0.937297,0.948519,1.936004
912534,detached,NaN,9.999157e+09,75.628194,20.198982,0.589085,NaN,NaN,NaN,step_SN,...,0.000000e+00,0.000000e+00,-7.432592e+49,1.357612e+00,0.322630,3.098686,1.050865,1.050865,1.050865,1.050868
946917,detached,NaN,9.997892e+09,2495.240714,2988.515309,0.257207,NaN,NaN,NaN,step_SN,...,0.000000e+00,0.000000e+00,-7.183882e+49,1.646766e-07,0.012170,3.973294,1.358343,1.358784,1.358343,1.358343
966537,detached,NaN,9.995129e+09,732.800353,478.618033,0.405960,NaN,NaN,NaN,step_SN,...,0.000000e+00,0.000000e+00,-7.596421e+49,7.561886e-07,0.047041,4.644605,1.204072,1.204072,1.204072,1.204089
972055,detached,NaN,9.982113e+09,116.699195,35.706447,0.681220,NaN,NaN,NaN,step_SN,...,0.000000e+00,0.000000e+00,-6.938840e+49,1.366819e-01,0.056530,3.488865,1.217440,1.217440,1.217440,1.223541
973736,detached,NaN,9.989924e+09,64.918223,16.344035,0.176487,NaN,NaN,NaN,step_SN,...,0.000000e+00,0.000000e+00,-6.868307e+49,1.330043e-06,0.073145,4.724150,1.084064,1.084064,1.084064,1.084280

In [ ]:
filtered_df[(filtered_df['S2_mass'] < 2.5) & (filtered_df['orbital_period'] < 3.5) ][cols]

,time,step_names,state,event,S1_state,S2_state,S1_mass,S2_mass,orbital_period
binary_index,,,,,,,,,
68561,3.691715e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,3.747350,1.911536,1.849214
199300,7.081756e+09,step_CO_HMS_RLO,detached,CC2,BH,H-rich_Core_H_burning,2.785568,0.091402,3.097021
495833,5.462662e+09,step_CO_HMS_RLO,detached,CC2,BH,H-rich_Core_H_burning,2.543167,0.084394,2.159860
563655,9.633998e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,4.352769,2.491193,2.778295
893211,8.068772e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,4.664751,2.208363,0.459428

In [ ]:
df.loc[34222][cols]

,time,step_names,state,event,S1_state,S2_state,S1_mass,S2_mass,orbital_period
binary_index,,,,,,,,,
34222,7.816161e+09,initial_cond,detached,ZAMS,H-rich_Core_H_burning,H-rich_Core_H_burning,18.488846,6.041695,673.205977
34222,7.826776e+09,step_HMS_HMS,RLO1,oCE1,H-rich_Shell_H_burning,H-rich_Core_H_burning,11.651054,6.150812,252.112118
34222,7.826776e+09,step_CE,detached,NaN,stripped_He_non_burning,H-rich_Core_H_burning,6.518232,6.117600,0.887240
34222,7.826784e+09,step_detached,detached,CC1,stripped_He_Core_C_depleted,H-rich_Core_H_burning,6.493311,6.117590,0.900957
34222,7.826784e+09,step_SN,detached,NaN,NS,H-rich_Core_H_burning,2.493044,6.117590,3.532180
34222,7.853264e+09,step_detached,RLO2,oRLO2,NS,H-rich_Core_H_burning,2.493044,6.111617,1.026671
34222,7.863070e+09,step_CO_HMS_RLO,RLO2,oCE2,BH,H-rich_Core_H_burning,3.329968,0.704356,0.183356
34222,7.863070e+09,step_CE,merged,oMerging2,BH,H-rich_Core_H_burning,3.329968,0.704356,0.183356
34222,1.380000e+10,step_merged,merged,NaN,BH,massless_remnant,3.329968,0.000000,NaN
34222,1.380000e+10,step_end,merged,END,BH,massless_remnant,3.329968,0.000000,NaN