In [385]:
import pandas as pd
from pathlib import Path
import numpy as np
import seaborn as sns

# from posydon.popsyn.binarypopulation import BinaryPopulation
# from posydon.binary_evol.binarystar import BinaryStar
# from posydon.binary_evol.singlestar import SingleStar
from posydon.popsyn.synthetic_population import Population
# from posydon.popsyn.synthetic_population import PopulationRunner
# import astropy.units as u
# 
# import os
# import shutil
# from posydon.config import PATH_TO_POSYDON

from POSYDONHRDiagramModule import HR_Diagram

import matplotlib.pyplot as plt
import matplotlib as mpl

import random as rand 

from collections import Counter

DataPath = Path().resolve().parent / 'Data'

In [386]:
cols = ['time', 'step_names', 'state', 'event', 'S1_state', 'S2_state', 'S1_mass', 'S2_mass', 'orbital_period']
finCols = [
    'orbital_period_f',
    'eccentricity_f',
    'state_f',

    'S1_state_f',
    'S2_state_f',
    
    'S2_mass_f',
    'S2_log_R_f',
    'S2_log_L_f',


    'S1_mass_f',
    'S1_log_R_f',
    'S1_log_L_f'

 ]

initCols = [
    'orbital_period_i',
    'eccentricity_i',
    'state_i',

    'S2_state_i',
    'S2_mass_i',
    'S2_log_R_i',

    'S1_state_i',
    'S1_mass_i',
    'S1_log_R_i'
 ]

In [387]:
mpl.use("pgf")

mpl.rcParams.update({
    "pgf.texsystem": "pdflatex",  
    "font.family": "serif",       
    "text.usetex": True,          
    "pgf.rcfonts": False,         
})

In [388]:
def basicColHist(df, var: str, title: str | None = None, xLabel: str | None = None, saveFig: bool = False) -> None:
    fig, ax = plt.subplots(figsize=(6, 4))
    
    sns.histplot(df[var], bins=50, ax=ax)
    
    if title is None:
        title = f'{var} of BH-Sol systems at S1 SN'
    if xLabel is None:
        xLabel = var

    ax.set_title(title)
    ax.set_xlabel(xLabel)
    ax.set_ylabel('Count')

    if saveFig:
        plt.savefig(title.replace(' ', '_') + '.pgf', bbox_inches='tight')

    plt.show()


def xVsY(
    df, xvar: str, yvar: str,
    title: str | None = None,
    xLabel: str | None = None,
    yLabel: str | None = None,
    saveFig: bool = False,
    savePath:Path = Path(),
    fit: bool = False,
    ci: int = 95  
) -> None:
    fig, ax = plt.subplots(figsize=(8, 5))

    if fit:
        sns.regplot(
            data=df, x=xvar, y=yvar,
            ci=ci,                            
            line_kws={"color": "red", "linestyle": "--", "linewidth": 2},
            scatter_kws={"alpha": 0.6},
            ax=ax
        )
    else:
        sns.scatterplot(data=df, x=xvar, y=yvar, alpha=0.6, ax=ax)

    if title is None:
        title = f'{xvar} vs {yvar} of BH-Sol systems at S1 SN'
    if xLabel is None:
        xLabel = xvar
    if yLabel is None:
        yLabel = yvar

    ax.set_title(title)
    ax.set_xlabel(xLabel)
    ax.set_ylabel(yLabel)

    if saveFig:
        name = title.replace(' ', '_') + '.pgf'
        plt.savefig((savePath / name), bbox_inches='tight')

    plt.show()

In [389]:
pop = Population(str(DataPath / 'SunLikeStar_Filt' / 'BH_Sol_Filtered_1e+00_Zsun_population.h5'))

In [390]:
bhSolRows = pd.read_csv(DataPath /'SunLikeStar_Filt' / 'BH_Sol_Filtered_1e+00_Zsun_population.csv')

In [391]:
bhSolRows = bhSolRows.drop(17, axis='index')

In [392]:
bhSolRows

,binary_index,state,event,time,orbital_period,eccentricity,lg_mtransfer_rate,step_names,step_times,S1_state,...,S2_he_core_mass,S2_he_core_radius,S2_co_core_mass,S2_co_core_radius,S2_center_h1,S2_center_he4,S2_surface_h1,S2_surface_he4,S2_surf_avg_omega_div_omega_crit,S2_spin
0,22892,detached,NaN,4.498900e+09,1.494220,0.360938,NaN,step_SN,0.002222,BH,...,0.0,NaN,0.0,0.0,0.691616,0.294023,0.7155,0.270271,0.105856,3.023514
1,30640,detached,NaN,8.381730e+09,1.884652,0.142856,NaN,step_SN,0.004856,BH,...,0.0,NaN,0.0,0.0,0.696244,0.289355,0.7155,0.270271,0.125305,3.578513
2,98004,detached,NaN,9.548856e+09,2.740360,0.351989,NaN,step_SN,0.003183,BH,...,0.0,NaN,0.0,0.0,0.695545,0.290039,0.7155,0.270271,0.097579,2.769272
3,152104,detached,NaN,2.025330e+09,0.796016,0.669528,NaN,step_SN,0.001699,BH,...,0.0,NaN,0.0,0.0,0.705203,0.280193,0.7155,0.270271,0.032131,0.904615
4,197243,detached,NaN,8.824689e+09,3.317456,0.600119,NaN,step_SN,0.002589,BH,...,0.0,NaN,0.0,0.0,0.695127,0.290483,0.7155,0.270271,0.080369,2.296414
5,214571,detached,NaN,9.934345e+09,6.844816,0.716792,NaN,step_SN,0.003830,BH,...,0.0,NaN,0.0,0.0,0.701769,0.283705,0.7155,0.270271,0.033424,0.937796
6,217672,detached,NaN,9.226441e+09,7.859836,0.598014,NaN,step_SN,0.003460,BH,...,0.0,NaN,0.0,0.0,0.704175,0.281255,0.7155,0.270271,0.030181,0.845591
7,227670,detached,NaN,3.143854e+08,52.749603,0.663875,NaN,step_SN,0.004207,BH,...,0.0,NaN,0.0,0.0,0.698373,0.287186,0.7155,0.270271,0.039821,1.129760
8,234637,detached,NaN,8.256869e+09,15.899186,0.622247,NaN,step_SN,0.004924,BH,...,0.0,NaN,0.0,0.0,0.696121,0.289475,0.7155,0.270271,0.050934,1.452895
9,271714,detached,NaN,7.629761e+09,14.974814,0.357936,NaN,step_SN,0.003989,BH,...,0.0,NaN,0.0,0.0,0.696206,0.289376,0.7155,0.270271,0.048040,1.364186
10,277127,detached,NaN,6.377914e+09,17.206798,0.640577,NaN,step_SN,0.004099,BH,...,0.0,NaN,0.0,0.0,0.703723,0.281722,0.7155,0.270271,0.036724,1.029227
11,300689,detached,NaN,7.277042e+09,4.314119,0.183835,NaN,step_SN,0.002598,BH,...,0.0,NaN,0.0,0.0,0.701054,0.284430,0.7155,0.270271,0.040783,1.144935
12,379156,detached,NaN,2.083792e+09,2.448846,0.287103,NaN,step_SN,0.004119,BH,...,0.0,NaN,0.0,0.0,0.703973,0.281464,0.7155,0.270271,0.054455,1.525818
13,411727,detached,NaN,6.365762e+08,10.076221,0.540476,NaN,step_SN,0.003870,BH,...,0.0,NaN,0.0,0.0,0.702518,0.282938,0.7155,0.270271,0.044947,1.259721
14,442981,detached,NaN,1.806681e+07,4.212360,0.511879,NaN,step_SN,0.004639,BH,...,0.0,NaN,0.0,0.0,0.695477,0.290129,0.7155,0.270271,0.077822,2.223385
15,457940,detached,NaN,3.378503e+09,22.673620,0.811249,NaN,step_SN,0.004610,BH,...,0.0,NaN,0.0,0.0,0.703280,0.282166,0.7155,0.270271,0.050840,1.424617
16,464365,detached,NaN,3.752248e+09,190.296092,0.736579,NaN,step_SN,0.011185,BH,...,0.0,NaN,0.0,0.0,0.705245,0.280154,0.7155,0.270271,0.023647,0.665088
18,495682,detached,NaN,5.650854e+09,11.747898,0.355708,NaN,step_SN,0.001500,BH,...,0.0,NaN,0.0,0.0,0.702880,0.282576,0.7155,0.270271,0.024255,0.679916
19,543603,detached,NaN,3.509486e+09,30.606112,0.831807,NaN,step_SN,0.004970,BH,...,0.0,NaN,0.0,0.0,0.697801,0.287771,0.7155,0.270271,0.091705,2.607587
20,571684,detached,NaN,5.580324e+09,3.749132,0.450663,NaN,step_SN,0.003920,BH,...,0.0,NaN,0.0,0.0,0.703218,0.282236,0.7155,0.270271,0.037986,1.064908
21,572991,detached,NaN,2.206456e+09,97.150411,0.926419,NaN,step_SN,0.005810,BH,...,0.0,NaN,0.0,0.0,0.695536,0.290067,0.7155,0.270271,0.116955,3.338412
22,592501,detached,NaN,3.968278e+09,96.805112,0.891984,NaN,step_SN,0.008790,BH,...,0.0,NaN,0.0,0.0,0.699453,0.286082,0.7155,0.270271,0.040270,1.138255
23,608998,detached,NaN,3.925850e+09,21.302996,0.750589,NaN,step_SN,0.001580,BH,...,0.0,NaN,0.0,0.0,0.690050,0.295590,0.7155,0.270271,0.063598,1.809829
24,689764,detached,NaN,9.659349e+09,25.968059,0.817735,NaN,step_SN,0.004174,BH,...,0.0,NaN,0.0,0.0,0.703911,0.281527,0.7155,0.270271,0.046766,1.310341
25,693622,detached,NaN,7.291424e+09,115.276003,0.527535,NaN,step_SN,0.002663,BH,...,0.0,NaN,0.0,0.0,0.702725,0.282729,0.7155,0.270271,0.025368,0.710908
26,695566,detached,NaN,3.784252e+09,1.593837,0.392804,NaN,step_SN,0.004401,BH,...,0.0,NaN,0.0,0.0,0.703285,0.282164,0.7155,0.270271,0.047492,1.330809
27,725987,detached,NaN,8.347180e+08,31.306367,0.756027,NaN,step_SN,0.001517,BH,...,0.0,NaN,0.0,0.0,0.698792,0.286746,0.7155,0.270271,0.034817,0.983676
28,726773,detached,NaN,8.661440e+09,12.031967,0.399027,NaN,step_SN,0.004209,BH,...,0.0,NaN,0.0,0.0,0.697547,0.288006,0.7155,0.270271,0.044702,1.264199
29,755405,detached,NaN,8.996695e+08,6.201866,0.716485,NaN,step_SN,0.002639,BH,...,0.0,NaN,0.0,0.0,0.696435,0.289129,0.7155,0.270271,0.064643,1.828451
30,762839,detached,NaN,5.635252e+08,16.027637,0.382796,NaN,step_SN,0.007749,BH,...,0.0,NaN,0.0,0.0,0.698026,0.287532,0.7155,0.270271,0.043702,1.238834
31,782773,detached,NaN,5.827303e+09,1.810091,0.504878,NaN,step_SN,0.007634,BH,...,0.0,NaN,0.0,0.0,0.702395,0.283074,0.7155,0.270271,0.054169,1.519996
32,787316,detached,NaN,8.308909e+09,5.708641,0.503511,NaN,step_SN,0.004863,BH,...,0.0,NaN,0.0,0.0,0.699201,0.286336,0.7155,0.270271,0.068012,1.922654
33,797031,detached,NaN,6.685444e+08,2.200238,0.650587,NaN,step_SN,0.004184,BH,...,0.0,NaN,0.0,0.0,0.695323,0.290265,0.7155,0.270271,0.062495,1.774209
34,821552,detached,NaN,9.968894e+09,2.831847,0.665931,NaN,step_SN,0.003888,BH,...,0.0,NaN,0.0,0.0,0.700799,0.284713,0.7155,0.270271,0.043386,1.223574
35,823596,detached,NaN,9.382755e+09,2.121067,0.346784,NaN,step_SN,0.004198,BH,...,0.0,NaN,0.0,0.0,0.700927,0.284566,0.7155,0.270271,0.053544,1.504639
36,827689,detached,NaN,1.134472e+09,9.757886,0.596340,NaN,step_SN,0.004594,BH,...,0.0,NaN,0.0,0.0,0.700498,0.285004,0.7155,0.270271,0.061212,1.721948
37,838767,detached,NaN,3.794077e+09,21.722308,0.850959,NaN,step_SN,0.004538,BH,...,0.0,NaN,0.0,0.0,0.697943,0.287621,0.7155,0.270271,0.088942,2.524241
38,844642,detached,NaN,8.394692e+09,7.901438,0.408438,NaN,step_SN,0.002800,BH,...,0.0,NaN,0.0,0.0,0.701827,0.283644,0.7155,0.270271,0.040880,1.146695
39,845451,detached,NaN,3.686023e+09,8.354087,0.423690,NaN,step_SN,0.004500,BH,...,0.0,NaN,0.0,0.0,0.700034,0.285486,0.7155,0.270271,0.054760,1.544667
40,869906,detached,NaN,1.854124e+09,23.211976,0.877597,NaN,step_SN,0.004843,BH,...,0.0,NaN,0.0,0.0,0.702200,0.283273,0.7155,0.270271,0.073418,2.060619
41,895474,detached,NaN,6.708661e+09,7.609664,0.596753,NaN,step_SN,0.004635,BH,...,0.0,NaN,0.0,0.0,0.698880,0.286672,0.7155,0.270271,0.085748,2.430863
42,897298,detached,NaN,5.121369e+08,2.080105,0.392528,NaN,step_SN,0.004618,BH,...,0.0,NaN,0.0,0.0,0.696582,0.289001,0.7155,0.270271,0.086182,2.450727
43,934041,detached,NaN,6.551001e+09,22.924889,0.762912,NaN,step_SN,0.004846,BH,...,0.0,NaN,0.0,0.0,0.699981,0.285535,0.7155,0.270271,0.034874,0.982661
44,962284,detached,NaN,5.114051e+09,22.285141,0.426132,NaN,step_SN,0.002838,BH,...,0.0,NaN,0.0,0.0,0.701442,0.284029,0.7155,0.270271,0.027050,0.758432
45,964912,detached,NaN,4.673036e+09,4.921996,0.099762,NaN,step_SN,0.001519,BH,...,0.0,NaN,0.0,0.0,0.693985,0.291636,0.7155,0.270271,0.062925,1.798383

In [393]:
# pop.calculate_formation_channels()

In [394]:
Counter(pop.formation_channels['channel'])

Counter({'ZAMS_oCE1_CC1_oRLO2_CC2_maxtime_END': 35,
         'ZAMS_oCE1_CC1_oRLO2_maxtime_END': 7,
         'ZAMS_oCE1_CC1_END': 3,
         'ZAMS_oRLO1_CC1_oRLO2_CC2_FAILED': 1})

In [395]:
pOneline = pop.oneline.select()
pHistory = pop.history.select()

In [396]:
pOneline = pOneline.drop(17, axis='index')
pHistory = pHistory.drop(17, axis='index')

In [397]:
bhSolRows[cols]

,time,step_names,state,event,S1_state,S2_state,S1_mass,S2_mass,orbital_period
0,4.498900e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,2.679673,2.998272,1.494220
1,8.381730e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,4.517730,2.945927,1.884652
2,9.548856e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,3.141908,2.671987,2.740360
3,2.025330e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,2.667703,1.613518,0.796016
4,8.824689e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,3.118031,2.971203,3.317456
5,9.934345e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,3.746899,2.079317,6.844816
6,9.226441e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,3.621245,1.854338,7.859836
7,3.143854e+08,step_SN,detached,NaN,BH,H-rich_Core_H_burning,4.164533,2.635615,52.749603
8,8.256869e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,4.515033,2.891355,15.899186
9,7.629761e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,3.932408,2.700722,14.974814
10,6.377914e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,3.908060,1.947468,17.206798
11,7.277042e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,3.090678,2.120806,4.314119
12,2.083792e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,4.083630,1.899742,2.448846
13,6.365762e+08,step_SN,detached,NaN,BH,H-rich_Core_H_burning,3.855308,1.979398,10.076221
14,1.806681e+07,step_SN,detached,NaN,BH,H-rich_Core_H_burning,4.492276,2.963743,4.212360
15,3.378503e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,4.084192,1.938489,22.673620
16,3.752248e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,3.171739,1.639073,190.296092
18,5.650854e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,2.577795,1.998451,11.747898
19,3.509486e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,4.671268,2.734941,30.606112
20,5.580324e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,3.842804,1.993194,3.749132
21,2.206456e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,4.850893,2.923248,97.150411
22,3.968278e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,4.322265,2.460498,96.805112
23,3.925850e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,2.577795,2.849636,21.302996
24,9.659349e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,4.083937,1.907977,25.968059
25,7.291424e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,3.173198,1.969506,115.276003
26,3.784252e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,4.078658,1.960416,1.593837
27,8.347180e+08,step_SN,detached,NaN,BH,H-rich_Core_H_burning,2.577795,2.447274,31.306367
28,8.661440e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,3.931764,2.500983,12.031967
29,8.996695e+08,step_SN,detached,NaN,BH,H-rich_Core_H_burning,3.090733,2.521811,6.201866
30,5.635252e+08,step_SN,detached,NaN,BH,H-rich_Core_H_burning,4.169876,2.601344,16.027637
31,5.827303e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,4.165716,2.072802,1.810091
32,8.308909e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,4.337370,2.473011,5.708641
33,6.685444e+08,step_SN,detached,NaN,BH,H-rich_Core_H_burning,4.084288,2.694433,2.200238
34,9.968894e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,3.915384,2.346994,2.831847
35,9.382755e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,4.164542,2.183495,2.121067
36,1.134472e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,4.324523,2.236858,9.757886
37,3.794077e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,4.339750,2.654473,21.722308
38,8.394692e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,3.196819,2.059597,7.901438
39,3.686023e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,4.324661,2.367227,8.354087
40,1.854124e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,4.501062,2.095701,23.211976
41,6.708661e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,4.491919,2.597278,7.609664
42,5.121369e+08,step_SN,detached,NaN,BH,H-rich_Core_H_burning,4.489263,2.754583,2.080105
43,6.551001e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,3.842967,2.321098,22.924889
44,5.114051e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,3.136510,2.042321,22.285141
45,4.673036e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,2.601071,2.998399,4.921996

In [398]:
pOneline[pOneline['S2_mass_i'] > 3]

Empty DataFrame
Columns: [state_i, event_i, time_i, orbital_period_i, eccentricity_i, lg_mtransfer_rate_i, step_names_i, step_times_i, S1_state_i, S1_mass_i, S1_log_R_i, S1_log_L_i, S1_lg_mdot_i, S1_he_core_mass_i, S1_he_core_radius_i, S1_co_core_mass_i, S1_co_core_radius_i, S1_center_h1_i, S1_center_he4_i, S1_surface_h1_i, S1_surface_he4_i, S1_surf_avg_omega_div_omega_crit_i, S1_spin_i, S2_state_i, S2_mass_i, S2_log_R_i, S2_log_L_i, S2_lg_mdot_i, S2_he_core_mass_i, S2_he_core_radius_i, S2_co_core_mass_i, S2_co_core_radius_i, S2_center_h1_i, S2_center_he4_i, S2_surface_h1_i, S2_surface_he4_i, S2_surf_avg_omega_div_omega_crit_i, S2_spin_i, state_f, event_f, time_f, orbital_period_f, eccentricity_f, lg_mtransfer_rate_f, step_names_f, step_times_f, S1_state_f, S1_mass_f, S1_log_R_f, S1_log_L_f, S1_lg_mdot_f, S1_he_core_mass_f, S1_he_core_radius_f, S1_co_core_mass_f, S1_co_core_radius_f, S1_center_h1_f, S1_center_he4_f, S1_surface_h1_f, S1_surface_he4_f, S1_surf_avg_omega_div_omega_crit_f, S1_spin_f, S2_state_f, S2_mass_f, S2_log_R_f, S2_log_L_f, S2_lg_mdot_f, S2_he_core_mass_f, S2_he_core_radius_f, S2_co_core_mass_f, S2_co_core_radius_f, S2_center_h1_f, S2_center_he4_f, S2_surface_h1_f, S2_surface_he4_f, S2_surf_avg_omega_div_omega_crit_f, S2_spin_f, S1_natal_kick_velocity, S1_natal_kick_azimuthal_angle, S1_natal_kick_polar_angle, S1_spin_orbit_tilt_second_SN, S1_f_fb, S1_SN_type, S1_h1_mass_ej, S1_he4_mass_ej, S1_avg_c_in_c_core_at_He_depletion, S1_co_core_mass_at_He_depletion, S2_natal_kick_velocity, S2_natal_kick_azimuthal_angle, S2_natal_kick_polar_angle, S2_natal_kick_mean_anomaly, S2_spin_orbit_tilt_first_SN, S2_spin_orbit_tilt_second_SN, S2_f_fb, S2_SN_type, S2_h1_mass_ej, S2_he4_mass_ej, S2_avg_c_in_c_core_at_He_depletion, S2_co_core_mass_at_He_depletion, interp_class_HMS_HMS, interp_class_CO_HMS_RLO, ...]
Index: []

[0 rows x 109 columns]

In [399]:
print(((pOneline['orbital_period_i'].describe()).to_frame().style.format().to_latex(column_format='|l|r|')).replace('_', '\_').replace('%', '\%'))

\begin{tabular}{|l|r|}
 & orbital\_period\_i \\
count & 45.000000 \\
mean & 4150.149389 \\
std & 158.999350 \\
min & 3844.570082 \\
25\% & 4016.808617 \\
50\% & 4170.976368 \\
75\% & 4273.375834 \\
max & 4390.052803 \\
\end{tabular}

In [400]:
print(((pOneline['S2_mass_i'].describe()).to_frame().style.format().to_latex(column_format='|l|r|')).replace('_', '\_').replace('%', '\%'))

\begin{tabular}{|l|r|}
 & S2\_mass\_i \\
count & 45.000000 \\
mean & 2.195909 \\
std & 0.348479 \\
min & 1.551266 \\
25\% & 1.880662 \\
50\% & 2.188940 \\
75\% & 2.474821 \\
max & 2.753904 \\
\end{tabular}

In [401]:
print(((pOneline['S1_mass_i'].describe()).to_frame().style.format().to_latex(column_format='|l|r|')).replace('_', '\_').replace('%', '\%'))

\begin{tabular}{|l|r|}
 & S1\_mass\_i \\
count & 45.000000 \\
mean & 16.826121 \\
std & 1.107231 \\
min & 14.878710 \\
25\% & 16.077692 \\
50\% & 16.665842 \\
75\% & 17.672163 \\
max & 19.435080 \\
\end{tabular}

In [402]:
pOneline['eccentricity_f'].describe()

count    45.000000
mean      0.044134
std       0.167015
min       0.000000
25%       0.000000
50%       0.000000
75%       0.000000
max       0.669528
Name: eccentricity_f, dtype: float64

In [403]:
graphSave = Path.cwd().parent / 'Reports' /'3_23_26' / 'graphs'

In [404]:
basicColHist(bhSolRows, 'eccentricity')

In [405]:
basicColHist(bhSolRows,'S2_mass')

In [406]:
basicColHist(bhSolRows,'S1_mass')

In [407]:
basicColHist(bhSolRows,'orbital_period', saveFig=True)

In [408]:
# HR_Diagram(bhSolRows,
#            'BhSol',
#            Star_Radius=15)

In [409]:
xVsY(pOneline, 'S1_mass_i', 'S2_mass_i', title='Intial Masses of BH-Sol progenitors', fit=True, saveFig=True, savePath=graphSave)

In [410]:
xVsY(bhSolRows, 'S1_mass', 'S2_mass', title='BH-Sol Masses at Initial Formation', fit=True, saveFig=True, savePath=graphSave)